### ISSUE TITLE
How to create PR on upstream repo from branch and action running in my fork

### ISSUE THREAD

**Issue by corneliusroemer** [peter-evans/create-pull-request#1003]
I want to create a PR from a branch in my fork to an upstream repo, in an action running in the fork.

Can I do this with this action? I couldn't figure out from the documentation.

I've already got a branch on my fork. I just need to open the PR to the upstream repo.

**Comment by corneliusroemer** [comment]
I guess it's not possible, not least due to the Github token having only permission for the repo the action is running in?

One can do this using `gh` CLI quite conveniently:
```
- run: gh pr create --head corneliusroemer:update/nextclade -d --title "Update Nextclade" --body ""
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION }}
```

But the secret needs to be added manually with more permissions.

**Comment by peter-evans** [comment]
Hi @corneliusroemer 

No matter what you are doing in a GitHub actions workflow, if you need write/create access to a remote repo then you need a secret containing a PAT with permissions to access it. The default `GITHUB_TOKEN` is scoped to the current repo (your fork).

If you have control of the parent repo then you might be able to run your workflow there and use the fork as described in the following link. This might not fit your use case.
https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#push-pull-request-branches-to-a-fork

If you already have a branch in your fork then you are doing half of this actions job, and it might be easier to just call the GitHub API using [github-script](https://github.com/actions/github-script). I suggest checking out some of the [examples](https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md) in the documentation to get a better idea of how this action works and whether it would be suitable for your use case. Often it's possible to redesign a workflow to take full advantage of this action's functionality.

**Comment by parteekcoder** [comment]
> - run: gh pr create --head corneliusroemer:update/nextclade -d --title "Update Nextclade" --body ""
>         env:
>           GITHUB_TOKEN: ${{ secrets.ACTION }}

Hi @corneliusroemer , may I know what permissions you gave to token ?
