### ISSUE TITLE
Feature request: Allow enabling auto-merge

### ISSUE THREAD

**Issue by RappC** [peter-evans/create-pull-request#1009]
Would be great if a flag would be added where one can enable auto-merge feature of pull requests as described at https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request

**Comment by peter-evans** [comment]
Hi @RappC 

See the docs here for details about how to auto-merge PRs created by this action.
https://github.com/peter-evans/create-pull-request#auto-merge

**Comment by mbrevda** [comment]
Looking into using this action and wondering: would it be hard to add an auto-merge option to _this_ action so that another step isn't necessary? Or perhaps there is a downside to doing so that I'm missing?

**Comment by peter-evans** [comment]
@mbrevda I deliberately made it a separate action so it can be reused in other contexts. I'm my opinion, actions should do one thing and do it well. I try not bloat this action with features and break things out into separate actions where I think it makes sense.
