### ISSUE TITLE
How to open PR to developer when PR to master opened

### ISSUE THREAD

**Issue by daurenalipbekov** [peter-evans/create-pull-request#1021]
Is it possible to create PR for example to developer branch, when PR to master created with all labels, assignees? In other words, full copy of PR created to master only changing base branch to developer.

**Comment by peter-evans** [comment]
Hi @daurenalipbekov 

Please see this example to help you write a workflow for that use case.
https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another
