### ISSUE TITLE
Create PR in different repo?

### ISSUE THREAD

**Issue by rkleinman-hpe** [peter-evans/create-pull-request#1041]
### Subject of the issue

Is it possible to use this action to create a PR in a different repository?

**Comment by peter-evans** [comment]
Hi @rkleinman-hpe 

Yes. Please see the docs here:
https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#creating-pull-requests-in-a-remote-repository

**Comment by rkleinman-hpe** [comment]
Thanks!
