### ISSUE TITLE
[Question] How can I create a cross pull request from my fork to parent repo

### ISSUE THREAD

**Issue by newbe36524** [peter-evans/create-pull-request#1042]
### Subject of the issue

I want to create a pull request from my fork repo to parent repo which is not owned by me and I have no write access to.

### Steps to reproduce

1. there is a public repo dapr/docs which I have no access to write.
2. I fork it into my account as newbe36524/docs
3. I want to create pull request in github action in newbe36524/docs repo (fork repo)
4. it is almost impossible to create a github action in parent repo, I have to write github action in forked repo.

actually, I do some try but does not work:

https://github.com/newbe36524/docs/blob/main/.github/workflows/pull_request_to_dapr_docs.yml

**Comment by newbe36524** [comment]
I think it could be anwser: https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#creating-pull-requests-in-a-remote-repository

Please close this issue if I am right, because I have already created PR manually and have no chance to test it immediately

**Comment by peter-evans** [comment]
Hi @newbe36524 

This action is not really designed to be used in cases where you are not an owner/collaborator of the pull request target. It's for automating pull request creation tasks in a workflow, so generally that should be done by the owner/collaborator. If you are just creating a one-off pull request to a repository owned by someone else then this is not the right tool.

**Comment by newbe36524** [comment]
@peter-evans  Many Thanks.
