### ISSUE TITLE
Use for branches already created?

### ISSUE THREAD

**Issue by rkleinman-hpe** [peter-evans/create-pull-request#1043]
### Subject of the issue

My repository already has changes pushed to a branch. Can I just use this action to create a PR with a source and target branch?

**Comment by peter-evans** [comment]
Hi @rkleinman-hpe 

The action is not really designed to work with existing branches that you just want to merge and delete. In that situation, most of the work has already been done and all you need to do is call the GitHub API to make a pull request. If this fits your use case I would recommend using [github-script](https://github.com/actions/github-script).

If, however, you have a use case were you want to continually merge changes between two existing branches, then this example might help:
https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another

**Comment by rkleinman-hpe** [comment]
Thanks @peter-evans , basically I want to keep merging the master/main branch back to develop in gitflow (where neither branch should be deleted, and are in fact protected branches. When I attempt to do this, the action gives an error with no message: https://github.com/Cray-HPE/cray-product-catalog/runs/4946551386?check_suite_focus=true

I'll check out your links and see if either fit, thanks!

**Comment by peter-evans** [comment]
For that case, the example I linked should be a fit for what you want to do.

**Comment by rkleinman-hpe** [comment]
Got is all wired up, it worked. Thanks!
