### ISSUE TITLE
example on how to create a pull request and reuse in a later step

### ISSUE THREAD

**Issue by soloturn** [peter-evans/create-pull-request#1054]
i was wondering how to create a pull request and reuse it in another job. on the command line one can do:
```̀
pr=1731 git fetch origin pull/$pr/head:pr-$pr && git checkout pr-$pr
```
and if yes, it would be great to have it included in the example.

**Comment by peter-evans** [comment]
Hi @soloturn 

The action will output the pull request number, which you can then pass to another job in your workflow.

See details of the outputs here:
https://github.com/peter-evans/create-pull-request#action-outputs

I don't have a detailed example, but I recommend using [github-script](https://github.com/actions/github-script) to call the GitHub API if you need to.
