### ISSUE TITLE
Trying to avoid force push of identical PR changes

### ISSUE THREAD

**Issue by joelnotified** [peter-evans/create-pull-request#1062]
### Subject of the issue
I'm using this in an automated GHA that runs once per day. It will compare the latest available CLI version of a tool and compare that version to what's configured in a yaml file in the repository. If there is a new version, that version is set in the yaml file and a PR is created.

My issue is that under some circumstances this will trigger a force push every time it runs, even if there are no new CLI versions, as long as we haven't merged the original PR. I don't mind the force push, it's more that we get an email every day saying "Hey! There is a new CLI version available!" until we merge the PR. 

### Steps to reproduce
I thiiiiiink this is what happens:

1. Our GHA will checkout `main` and detect a new CLI version and update the file. `create-pull-request` will create a PR on a new branch, let's call it `update-cli-version`.
2. Later that day, we commit (unrelated) things to `main`.
3. The next morning, our GHA will checkout `main` once again and again detect the same new CLI version, since we haven't merged `update-cli-version` yet. `create-pull-request` will create a new temporary branch (`tmp-branch`) with the changes. It will compare `tmp-branch` with `update-cli-version` and it will get a diff (because of the new commits on `main` in step 2). It will force push `update-cli-version` with the changes from `tmp-branch`. 
4. The end result is that we have an identical PR as we did after step 1, since nothing else has really changed in that file.

I thought that `add-paths` could help against this, so that only those files were being compared in step 3, but I guess that's not the case. 

Is there something I can do to change this behavior? Should the `update-cli-version` branch be rebased before being compared to `tmp-branch`? I guess that would introduce other problems. 

I would be happy to contribute some kind of solution to this, if possible.

**Comment by jooooel** [comment]
Thanks a lot for a quick and informative reply @peter-evans ! 

Both of your suggestions sound like good workarounds, so I’ll proceed with that.

**Comment by joelnotified** [comment]
Thanks a lot for a quick and informative reply @peter-evans ! 

Both of your suggestions sound like good workarounds, so I’ll proceed with that.
