### ISSUE TITLE
Whats the best way to keep two repos in sync?

### ISSUE THREAD

**Issue by bschnurr** [peter-evans/create-pull-request#1063]
### Subject of the issue

Whats the best way to keep two repos in sync?

I have A repo with a subrepo B and I'm trying to run a workflow in A that pulls B, creates a PR in A then pushes to B and creates a PR in B

all while using a bot account which also trying other PR verification workflows.

Thank you

### Steps to reproduce

If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.

**Comment by peter-evans** [comment]
Hi @bschnurr 

I don't quite understand the exact scenario, but in general you should be able to boil this problem down to "how do I keep two branches in sync," regardless of what repo they exist in.

For the general solution, see this example:
https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another

**Comment by bschnurr** [comment]
Thanks for you response. that example is close to what I want but I think my core issue is more how to I specify an external repo in the call to 
` - name: Create PR in External Rep
        uses: peter-evans/create-pull-request@v3
        with:
`

something like 
` - name: Create PR in External Rep
        uses: peter-evans/create-pull-request@v3
        with:
		  base: externalRepo/main
          branch: userepo-update
			  
`

**Comment by peter-evans** [comment]
This section of the docs should help with that.
https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#creating-pull-requests-in-a-remote-repository

**Comment by bschnurr** [comment]
sorry i didn't see that before thanks!
