### ISSUE TITLE
Bump major version when upgrading to node16

### ISSUE THREAD

**Issue by FlemmingBehrend** [peter-evans/create-pull-request#1077]
### Subject of the issue

We are using your action on a github enterprise solution. The GitHub enterprise version is behind compared to the github.com  version. Therefore `node16` is not available there before we upgrade our enterprise solution.

This cause an error when trying to download your action.

GitHub actions like [github-scripts](https://github.com/actions/github-script/releases) creates a new major version when implementing changes that will impact github enterprise users.

Is it possible release the action with a new major version tag?

### Steps to reproduce

Running the action on a GitHub enterprise that only supports `node12` will cause the following error:

```bash
Download action repository 'actions/github-script@v5' (SHA:441359b1a30438de65712c2fbca0abe4816fa667)
Download action repository 'actions/checkout@v2' (SHA:5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f)
Download action repository 'actions/setup-node@v2.3.0' (SHA:aa759c6c94d3800c55b8601f21ba4b2371704cb7)
Download action repository 'peter-evans/create-pull-request@v3' (SHA:89265e8d24a5dea438a2577fdc409a11e9f855ca)
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node16' is not supported, use 'docker' or 'node12' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load peter-evans/create-pull-request/v3/action.yml
```

**Comment by peter-evans** [comment]
Hi @FlemmingBehrend 

Apologies for causing this issue, and thank you for reporting it. I had no idea GitHub Enterprise could not use node 16.

I've created a new release, `v3.14.0` / `v3`, which reverts the node runtime back to node 12.

I'll research this a bit more before attempting a runtime update again.

**Comment by peter-evans** [comment]
> I'll research this a bit more before attempting a runtime update again.

Scratch that. I see that GitHub Enterprise supports _only_ node 12. So I won't be updating this action's runtime for now.

**Comment by FlemmingBehrend** [comment]
@peter-evans thanks for reverting it. You could release the use of `node16` under major tag `v4`. In that case it would still work and we would update to `v4` when GitHub enterprise supports `node16`.

But I have testet out our script after your update and it works 👍 Thanks a lot.

**Comment by peter-evans** [comment]
So it turns out that Node 12 is EOL on 30 Apr 2022. That's why many of the official GitHub actions are releasing new major versions supporting node 16 recently. Perhaps that also means it will soon be supported in GHE. 🤷‍♂️ 

I think perhaps it does make sense to release a major version on Node 16, since Node 12 will be EOL in 2 months time. I will give this some consideration.

**Comment by peter-evans** [comment]
I just noticed this https://github.com/actions/checkout#whats-new
> Updated to the node16 runtime by default
> This requires a minimum [Actions Runner](https://github.com/actions/runner/releases/tag/v2.285.0) version of v2.285.0 to run, which is by default available in GHES 3.4 or later.

It's supported in the latest release candidate.
https://docs.github.com/en/enterprise-server@3.4/admin/release-notes#3.4.0.rc1

**Comment by FlemmingBehrend** [comment]
We have a planed update within the next week or two. 

If you release it as a major version we will update our workflows after the update. 

If you release it under a minor tag, then we will correct our workflows to v3.1.12 and then back to v3 after the update.

We prefer the major tag solution but we can handle the other we a little more work. 👍

**Comment by peter-evans** [comment]
Released the node 16 runtime update as `v4`.

**Comment by lilith** [comment]
The readme still references v3.
