### ISSUE TITLE
Ignoring files from gitignore feature not respecting negation

### ISSUE THREAD

**Issue by ChipWolf** [peter-evans/create-pull-request#1093]
### Subject of the issue

We have a pattern in our `.gitignore` that looks like this:
```
*.json
!*_en_us.json
```

This works in practice, with git. However, with the `create-pull-request` action, it does not include the negated `*_en_us.json` files in the pull request.

### Steps to reproduce

```bash
$ cat <<EOF > .gitignore
*.json
!*_en_us.json
EOF
$ touch file_en_us.json
$ touch file_de_de.json
$ git add -A
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:  file_en_us.json
```

Notice on `git status` the negated `file_en_us.json` file is untracked and any other `.json` file is ignored as expected.
However, observe that if a PR is created by `create-pull-request`, there are no `.json` files at all.

**Comment by peter-evans** [comment]
Hi @ChipWolf 

The action doesn't do anything special with respect to the `.gitignore` file. So it's difficult to guess what is going on in your case.

Please could you share the workflow you are using, and ideally the Actions log of the run where the `.json` files were not included.

**Comment by ChipWolf** [comment]
This seems to have been a transient issue with our complex workflow, I no longer believe it's an upstream issue.
Thanks for your time
