### ISSUE TITLE
Creating a pull request from the checked out branch to merge with an existing branch

### ISSUE THREAD

**Issue by Deelane** [peter-evans/create-pull-request#1094]
### Subject of the issue

Creating a pull request from the checked out branch to merge with an existing branch

### Details

I am currently trying to use actions to recreate a pull request that has just been merged but in a different branch. I previously attempted to do so with this code which I know is incorrect:

      `- name: 'Open pull request to merge with staging branch'
        uses: peter-evans/create-pull-request@v3
        with:
          base: staging
          branch: ${{ env.BRANCH_NAME }}`
          
I saw in the docs that branch is actually just a new branch to be created. But my question is, is there a way to take the branch stored in env.BRANCH_NAME and open a pull request to merge with the base branch? (in this case staging)

**Comment by peter-evans** [comment]
Hi @Deelane 

It sounds like you would like to create a pull request from a branch (develop?) to keep staging in sync. If so, this example should help you.
https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another

**Comment by Deelane** [comment]
That is definitely what I am trying to do. I did a trial run and I am not sure if I am using it as intended? The pull request is not being created and I would greatly appreciate your input, here is my code:

`      - name: 'Checkout dev pull request code'
        uses: actions/checkout@v2
        with:
          ref: staging  

      - name: 'Reset dev/feature branch'
        run: |
          git fetch origin ${{ env.BRANCH_NAME }}:${{ env.BRANCH_NAME }}
          git reset --hard ${{ env.BRANCH_NAME }}

      - name: Create pull request to merge with staging
        uses: peter-evans/create-pull-request@v3
        with:
          branch: dev/feature-staging-merge
`

From my understanding, staging is the branch that needs to be updated and kept in sync with a dev/feature branch (stored in env.BRANCH_NAME). So I check out staging, fetch the dev/feature branch and create a new branch called dev/feature-staging-merge from the dev/feature branch along with a pull request to merge with staging. Is my understanding correct? For reference, here are the errors that I am getting.

`Create or update the pull request branch
  /usr/bin/git symbolic-ref HEAD --short
  staging
  Working base is branch 'staging'

  Switched to a new branch 'branch_hash_1'
  Resetting working base branch 'staging'
  /usr/bin/git checkout --progress staging --
  Switched to branch 'staging'
  Your branch is up to date with 'origin/staging'.
  /usr/bin/git reset --hard origin/staging
  HEAD is now at branch_hash_2 Update push-to-uat.yml
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --unshallow origin dev/feature-staging-merge:refs/remotes/origin/dev/feature-staging-merge
  fatal: couldn't find remote ref dev/feature-staging-merge
  Pull request branch 'dev/feature-staging-merge' does not exist yet.
  /usr/bin/git checkout --progress -B dev/feature-staging-merge branch_hash_1 --
  Switched to a new branch 'dev/feature-staging-merge'
  /usr/bin/git rev-list --right-only --count staging...dev/feature-staging-merge
  0
  Branch 'dev/feature-staging-merge' is not ahead of base 'staging' and will not be created
  /usr/bin/git rev-parse HEAD
 branch_hash_2
  /usr/bin/git branch --delete --force branch_hash_1
  Deleted branch branch_hash_1 (was branch_hash_2)
Restore persisted git credentials`

**Comment by Deelane** [comment]
False alarm! My code is correct but I was attempting to do it in a separate job so ${{ env.BRANCH_NAME }} was not carried over. Thank you for the help!
