### ISSUE TITLE
Push fails with very big changeset

### ISSUE THREAD

**Issue by 3v1n0** [peter-evans/create-pull-request#1097]
### Subject of the issue

It looks like that when many changes are going to be pushed, the workflow fails:

```
Pushing pull request branch to 'origin/auto-rendered-icons'
  /usr/bin/git push --force-with-lease origin HEAD:refs/heads/auto-rendered-icons
  To https://github.com/ubuntu/yaru
   ! [remote rejected]     HEAD -> auto-rendered-icons (refusing to allow a GitHub App to create or update workflow `.github/workflows/open-pr-on-rendered-icons-changed.yaml` without `workflows` permission)
  error: failed to push some refs to 'https://github.com/ubuntu/yaru'
  Error: The process '/usr/bin/git' failed with exit code 1
```

With the very same action, but performing just few changes, it works like a charm.

Not sure if retrying makes sense. It's weird as I do have permissions and similar actions (and this very same too, in other conditions) work with no problem (sharing the same token).

### Steps to reproduce

Open a big repo, modify hundreds (or thousands) of files, try to push.

**Comment by 3v1n0** [comment]
An example is here:

A failure example is here https://github.com/3v1n0/yaru/runs/5607955412?check_suite_focus=true

It seems also to be somewhat racy because then the very same pipeline succeeded (no change happened on my settings or to the token): https://github.com/3v1n0/yaru/runs/5608514346?check_suite_focus=true

Here you can see the kind of changes we're talking about https://github.com/3v1n0/yaru/commits/rendered-icons

**Comment by peter-evans** [comment]
Hi @3v1n0 

The error message in the log snippet you provided says:

> refusing to allow a GitHub App to create or update workflow `.github/workflows/open-pr-on-rendered-icons-changed.yaml` without `workflows` permission

GitHub protects files in `.github/workflows/` by requiring additional permissions to update. You need to give the token the `workflows` permission if you want changes to workflow files to be raised in the PR.
