### ISSUE TITLE
Allow files as input for PR/Commit bodies

### ISSUE THREAD

**Issue by donmahallem** [peter-evans/create-pull-request#1098]
### Subject of the issue

Currently non 'static' inputs for bodies with multiline are a hassle to deal with in github actions.
For example if I do create release notes with a cli script wanting to use it with this actions it involves some ["workarounds"](https://trstringer.com/github-actions-multiline-strings/) it would be nice to specify files to be used as source for the body like some other actions allow it.

**Comment by peter-evans** [comment]
Hi @donmahallem 

I understand that it's not super-straightforward to deal with multiline content in GitHub actions. I have the same workaround snippet documented here: https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#setting-the-pull-request-body-from-a-file

As for providing file inputs, this is often requested for a number of the actions that I maintain. I've thought about it a lot and decided not add file IO features like this. I think actions should do one thing and do it well, and I'm trying very hard to keep the input interfaces of the actions I maintain clean and not bloat them with features. If I add something like this, other users will come along and ask for templating features or other content modification. After seeing the many different use cases that people have, it just makes sense to me for them to be handled in separate steps. I could never make a one-solution-fits-all feature, there would always be something extra that users need. I don't want to get into that situation.

What would be great is if GitHub added a special function to escape and preserve newlines. Then you could do something like `body: ${{ escape(steps.get-pr-body.outputs.body) }}`.

Thank you for raising the issue, though. I appreciate the desire to improve the action. 👍

**Comment by donmahallem** [comment]
I do get your point and as multiline has been an issue with actions for quite some time now I would have liked there to be an "official" way as you proposed.

Otherwise great action, cheers!
