### ISSUE TITLE
Input to override remote URL

### ISSUE THREAD

**Issue by meidlinga** [peter-evans/create-pull-request#1161]
### Subject of the issue

I would like to create a PR on a different (Github)-Repository, than the one the Action would be running on and the changes would be.

It seems a quite simple change [here](https://github.com/peter-evans/create-pull-request/blob/f1a7646cead32c950d90344a4fb5d4e926972a8f/src/create-pull-request.ts#L54) to read the value from an input, and only use `tryGetRemoteUrl`, if the input is not set.

**Comment by peter-evans** [comment]
Hi @meidlinga 

Please see this section of the docs:
https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#creating-pull-requests-in-a-remote-repository
