### ISSUE TITLE
Is possible to create a pull request with signed commits?

### ISSUE THREAD

**Issue by diogopms** [peter-evans/create-pull-request#1162]
### Subject of the issue

Hi, i didn't figure out a way to create pull requests with verified signed commits. Is this possible on the action passing the GPG public key. Thanks

### Steps to reproduce
- Setting the "Signed commits" enabled on branch protection.
- All the PR should have signed commits.

**Comment by peter-evans** [comment]
Hi @diogopms 

Please see this section of the docs:
https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#gpg-commit-signature-verification
