### ISSUE TITLE
PR update fails: Cannot read property 'number' of undefined

### ISSUE THREAD

**Issue by dprotaso** [peter-evans/create-pull-request#1163]
### Subject of the issue

This PR is trying to be updated - https://github.com/knative-sandbox/.github/pull/191

### Steps to reproduce

Here is the run: https://github.com/knative-sandbox/knobots/runs/5872676236?check_suite_focus=true

**Comment by peter-evans** [comment]
Hi @dprotaso 

It appears that the action correctly detected that a pull request exists, but then for some reason failed to fetch the pull request in order to update it.

Are you experiencing this consistently? I tried to reproduce the issue, but couldn't.

**Comment by dprotaso** [comment]
Looks like it's consistent with this repo - is there some debugging I can turn on to capture more info?

**Comment by peter-evans** [comment]
Looking back through the [actions logs](https://github.com/knative-sandbox/knobots/actions) I can see that your workflow does the same thing for many repositories, but the only case that fails is update of the pull request when the repo is `knative-sandbox/.github`.

My suspicion is that the period prefix on the repository name is causing a bug of some kind. I'll try to investigate further.

**Comment by peter-evans** [comment]
I found the bug. The problem occurs because the fork of `knative-sandbox/.github` has been renamed from `.github` to `sandbox-dot-github`. When fetching the pull request, the action was not accounting for the possibility of that rename.

I've released a fix as version `v4.0.2` / `v4`.

Thank you for raising this issue!

**Comment by dprotaso** [comment]
Awesome thanks for the quick fix
