### ISSUE TITLE
Error while trying to create an empty PR

### ISSUE THREAD

**Issue by joltcoke** [peter-evans/create-pull-request#1174]
We have the following setup:

A workflow_dispatch action which fetches some external data and (if changed) commits them to a branch "external". As part of this action also create-pull-request is used to create a PR against main. It's exactly the setup as recommended here: https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another

If there is an external change everything works as expected. Commit is created and a PR is opened.

If no external change is fetched, then no commit is created but create-pull-request still tries to create a PR and fails with the following error:

`Error: Validation Failed: {"resource":"PullRequest","code":"custom","message":"No commits between main and external-pr"}
`

"git log --oneline origin/external ^origin/main" doesn't show anything.

If the preceding actions/checkout gets called with "fetch-depth: 0" then it seems to work. Not sure if that's the best solution?

**Comment by peter-evans** [comment]
Hi @joltcoke 

Without seeing the workflow itself I'm not sure exactly what you are doing. However, it sounds like the solution here is to just to not run the create-pull-request action step if there is nothing to commit. You can do that with a [condition on the step](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution).
