### ISSUE TITLE
createOrUpdate error message check is case sensitive

### ISSUE THREAD

**Issue by lucasprograms** [peter-evans/create-pull-request#1176]
### Subject of the issue

The [check on line 70](https://github.com/peter-evans/create-pull-request/blob/main/src/github-helper.ts#L70) of github-helpers is case-sensitive.

When the action is triggered again, if repo name is not cased correctly, it performs a check like

`'A pull request already exists for MyOrg/my_repo'.includes('A pull request already exists for myorg/my_repo')`

I could certainly see a rationale for not considering this a bug, and requiring that the repo name be case-sensitive. In that case it might be worth throwing an error on that inconsistency early in the process.

### Steps to reproduce

* under the repository option, write the name in lower case, e.g., `myorg/my_repo` for `MyOrg/my_repo`
* trigger the action
* trigger the action again

Expected:
Action handles existence of pull request

Actual:
Error is thrown, e.g., `A pull request already exists for MyOrg:my_repo`

**Comment by peter-evans** [comment]
Hi @lucasprograms 

Thank you for raising this issue. I think we can consider this a bug.

Perhaps the easiest fix is just to not include the `headBranch` in the condition.
```typescript
e.message.includes(`A pull request already exists for`)
```
I'll get this fixed!

**Comment by peter-evans** [comment]
Released a fix in `v4.0.3` / `v4`.

Thanks for reporting!
