### ISSUE TITLE
  Pull request branch 'add_meta-developers-_channel_2' does not exist yet.

### ISSUE THREAD

**Issue by MoatazAbdAlmageed** [peter-evans/create-pull-request#1184]
### Subject of the issue

it was working well but suddly I got this error 

```
orking base is branch 'main'
  /usr/bin/git checkout --progress -B d5dd2a74-32c0-4e8b-8c2f-ed17a2f43214 HEAD --
  Switched to a new branch 'd5dd2a74-32c0-4e8b-8c2f-ed17a2f43214'
  /usr/bin/git status --porcelain -unormal --
  /usr/bin/git diff --quiet --
  /usr/bin/git diff --quiet --staged --
  /usr/bin/git reset --hard
  HEAD is now at 189e0c7 wip
  /usr/bin/git clean -f -d
  Resetting working base branch 'main'
  /usr/bin/git checkout --progress main --
  Switched to branch 'main'
  Your branch is up to date with 'origin/main'.
  /usr/bin/git reset --hard origin/main
  HEAD is now at 189e0c7 wip
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --unshallow origin add_meta-developers-_channel_2:refs/remotes/origin/add_meta-developers-_channel_2
  fatal: couldn't find remote ref add_meta-developers-_channel_2
  Pull request branch 'add_meta-developers-_channel_2' does not exist yet.
  /usr/bin/git checkout --progress -B add_meta-developers-_channel_2 d5dd2a74-32c0-4e8b-8c2f-ed17a2f43214 --
  Switched to a new branch 'add_meta-developers-_channel_2'
  /usr/bin/git rev-list --right-only --count main...add_meta-developers-_channel_2
  0
  Branch 'add_meta-developers-_channel_2' is not ahead of base 'main' and will not b

```

### Steps to reproduce

go to https://github.com/MoatazAbdAlmageed/YouTube-Channels/runs/6344007715?check_suite_focus=true and check the logs

**Comment by peter-evans** [comment]
Hi @MoatazAbdAlmageed 

This is normal operation for the action, which is why the action completed successfully. It's just logging the fact that it tried to find a branch of that name, but it doesn't exist yet.

If you are wondering why a pull request was not created, it's because there was no diff with `main`. See in the log it says:

> Branch 'add_meta-developers-_channel_2' is not ahead of base 'main' and will not be created

**Comment by MoatazAbdAlmageed** [comment]
yes you are right .. works now :)

**Comment by MoatazAbdAlmageed** [comment]
Here https://github.com/MoatazAbdAlmageed/YouTube-Channels/commit/00208e750603c4e5c2521b57fe1c892001ca05e9 I create test.md and I added it in .gitignore so I had to remove rest variables
