### ISSUE TITLE
PR not get by another workflow

### ISSUE THREAD

**Issue by mariuszcharusta-tomtom** [peter-evans/create-pull-request#1196]
### PR not get by another workflow
When I create PR using plugin and I have second workflow with config
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - prod

The second workflow doesn't start after PR created of title updated

**Comment by peter-evans** [comment]
Hi @mariuszcharusta-tomtom 

Please see this section of the docs:
https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
