### ISSUE TITLE
Successful PR creation but empty outputs

### ISSUE THREAD

**Issue by Endermanbugzjfc** [peter-evans/create-pull-request#1200]
### Successful PR creation but empty outputs
My step depends on the PR number but it does not run. Even though the PR creation is successful.

I then have done several tests (with both checkout@v2 and v3) and found out that the outputs are empty from logs:
https://github.com/Endermanbugzjfc/HyundaiCommando/runs/7192440772?check_suite_focus=true#step:6:96

### Steps to reproduce
1. Add step to create PR with `id: cpr`
2. Add another step that runs `if: steps.cpr.outputs.pr_number`
3. Wait for PR to create
4. Check logs
5. Outputs are empty

### Workflow
https://github.com/Endermanbugzjfc/HyundaiCommando/blob/3e687feb44aff1ac96d96c374df2b41376b651e4/.github/workflows/php-cs-fixer-pr.yml#L31

**Comment by peter-evans** [comment]
Hi @Endermanbugzjfc 

`pr_number` is not the correct output name. Try `pull-request-number`.

See the readme for the outputs here: https://github.com/peter-evans/create-pull-request#action-outputs
