### ISSUE TITLE
fails if push-to-fork does not exist but outputs wrong url

### ISSUE THREAD

**Issue by robstoll** [peter-evans/create-pull-request#1245]
### Subject of the issue
push-to-fork is specified, the corresponding fork does not exist

Describe your issue here.
It's expected that it fails but it outputs the url of the repo and not of the fork which is a bit misleading when searching the error

### Steps to reproduce
specify push-to-fork with one which does not exist

If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.

See https://github.com/tegonal/gget/actions/runs/3080604471/jobs/4978197502#step:6:24
The error should be:
```
https://github.com/tegonal-bot/gget
Error: Not Found
```
and not tegonal/gget (note the `-bot`)

**Comment by peter-evans** [comment]
Hi @robstoll 

The `Error: Not Found` message is actually unrelated to the previous lines. However, you are right that the logging could be improved so it's more clear what the issue is. I will update this.

**Comment by peter-evans** [comment]
Thanks!

Released as `v4.1.2` / `v4`
