### ISSUE TITLE
Create Pull Request does not work when repository name ends in Xgit

### ISSUE THREAD

**Issue by campersau** [peter-evans/create-pull-request#1256]
### Subject of the issue

We have a reprository named "ungit" https://github.com/FredrikNoren/ungit and after updating the `create-pull-request` action to v4 it does not work anymore and reports "Error: Not Found". See https://github.com/campersau/ungit/actions/runs/3103556378/jobs/5027017692#step:7:111

I think the issue is that in https://github.com/peter-evans/create-pull-request/pull/1153 the `.git` suffix is ignored, but the regex is wrong as it does not escape the `.`.

### Steps to reproduce

Use the create-pull-request action with a repository which name ends in Xgit

---

I added some more logging in my own fork and you can see that the "ngit" suffix is missing:

```
Attempting creation of pull request {
    "owner": "campersau",
    "repo": "u", // <---------------- missing "ngit"
    "title": "Bump Dependencies",
    "head": "campersau:bumpdependencies",
    "base": "master",
    "body": "...",
    "draft": false
  }
```

**Comment by peter-evans** [comment]
Thank you for fixing this!

Released as `v4.1.3` / `v4`
