### ISSUE TITLE
`commit message` is cutoff in created PR in v4.1.3

### ISSUE THREAD

**Issue by alerickson0** [peter-evans/create-pull-request#1263]
### `commit message` is cutoff in the created PR in v4.1.3

When I use v4.1.3 of the GitHub Action to create a PR, I find the first part of the `commit message` is cutoff. Strangely the rest of the message is kept. Also, this issue does not occur in v4.1.2.

### Steps to reproduce

Apologies the GitHub Actions workflow I am using is in a private repo. But, I can provide a scrubbed version of the call to the GitHub Action in my GitHub Actions workflow:
`- name: Make PR in repo`
`  uses: peter-evans/create-pull-request@v4.1.3`
`  with:`
`    token: ${{ inputs.my_github_token }}`
`    commit-message: >`
`      ${{ inputs.jira_ticket_number != '' && format('[{0}] ', inputs.jira_ticket_number) || '' }}Release`
`      ${{ inputs.environment }} version ${{ inputs.image_version }}, PR triggered by ${{ inputs.pr_triggered_by }}`

Also, above this step there is the usual checkout of a repo where the PR will be created. Now, here are the steps to reproduce:

1. Trigger the work flow with all of the inputs filled in
2. See the result

Actual result: The create PR's commit message is cutoff and there is no Jira ticket number with surrounding brackets. Here is an example of the commit message:

Release my-env version v1.2.3, PR triggered by alerickson0

Expected result: The full commit message to appear like this:

[MY-123] Release my-env version v1.2.3, PR triggered by alerickson0

**Comment by peter-evans** [comment]
Hi @alerickson0 

I don't see how any recent changes could have caused this issue. There is nothing in the code that could truncate your commit message, so it's most likely a problem in your workflow. Please check your workflow again and make sure that the yaml is formatted correctly where you are building the `commit-message`.
