### ISSUE TITLE
Do not update `title`, `body`, `tags`, etc. if PR exists

### ISSUE THREAD

**Issue by EverStarck** [peter-evans/create-pull-request#1265]
### Subject of the issue

According to this:

> updated - The action returns this if the pull request branch is updated. This means there are changes to the PR diff. (This will not be returned if other inputs like title, body, labels, etc., are updated.)

Is there any way that if the PR already exists, it doesn't change the title, body, etc? Or know if it made the change?

**Comment by peter-evans** [comment]
Hi @EverStarck 

The action will always try to keep the PR state in sync with the action configuration, so it always tries to update the `title`, `body`, etc. This is fundamental to the design of the action.

If you don't want the PR to be updated after creation, then in your workflow you could detect if the PR branch exists and then just don't run the action. Or you could run with one of these [alternative strategies](https://github.com/peter-evans/create-pull-request#alternative-strategy---always-create-a-new-pull-request-branch). Although, there are downsides to that, as explained in the readme.
