### ISSUE TITLE
no_proxy doesn't appear to be honoured 

### ISSUE THREAD

**Issue by codefish1** [peter-evans/create-pull-request#1267]
### Subject of the issue
 We are using Github Enterprise with self hosted runners running behind a cooperate web proxy.

The no_proxy value is set, to include the specific host eg `github.foo.com` and also a `.foo.com` 

### Steps to reproduce

I can't share the  workflow, but use the action behind a proxy with the following set for the whole runner:
HTTPS_PROXY
HTTP_PROXY
NO_PROXY

**Comment by codefish1** [comment]
How come it's not using the default as documented in https://github.com/octokit/octokit.js/#proxy-servers-nodejs-only

I can make a change but I need to understand how to test the change correclty

**Comment by codefish1** [comment]
I _think_ it's caused by by there not been a proxy agent declared and used in [github_helper](https://github.com/peter-evans/create-pull-request/blob/671dc9c9e0c2d73f07fa45a3eb0220e1622f0c5f/src/github-helper.ts#L24)

**Comment by peter-evans** [comment]
Hi @codefish1 

Originally, I followed the advice here: https://github.com/octokit/octokit.js/issues/2098#issuecomment-844673894

But it now seems there is a better way to handle this and the new advice has been updated in the docs that you linked. I'm going to try changing the implementation so that the proxy environment variables are handled automatically.

**Comment by peter-evans** [comment]
@codefish1 It would be great if you could test the new implementation and check that it works well for you.

You can test it by changing the action version to `proxy`.
```yml
      - uses: peter-evans/create-pull-request@proxy
```

**Comment by peter-evans** [comment]
@codefish1 Thank you for testing it!

Released as `v4.2.0` / `v4`

**Comment by codefish1** [comment]
Sure, I'll make some time to look at it later this week.  Unfortunately I'm off sick with COVID atm

**Comment by codefish1** [comment]
Tested it just not and it all appears to be working fine

**Comment by peter-evans** [comment]
Great. Thank you for testing!

**Comment by peter-evans** [comment]
@codefish1 `v5.0.0` / `v5` is now released.

Please update to `v5`. I will remove pre-release versions after 4 weeks. Thank you for testing the pre-release version!
