### ISSUE TITLE
GitHub has started warning about use of `set-output` command

### ISSUE THREAD

**Issue by bavison** [peter-evans/create-pull-request#1298]
This has started appearing in my job logs, under the section "Setting outputs"

`Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
`

I assume the changes described in the blog post are a useful in resolving this?

**Comment by wojsmol** [comment]
@bavison This is fixed in `v4` starting from `v4.1.4`.

**Comment by bavison** [comment]
Can confirm v4.1.4 fixes the issue for me - many thanks! Hopefully this ticket will point anyone else who (like me) didn't find this obvious from the change logs.
