### ISSUE TITLE
Provide examples for how to use `team-reviewers`

### ISSUE THREAD

**Issue by menny** [peter-evans/create-pull-request#130]
I'm unable to correctly configure the `team-reviewers` field:
https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/2085/files

**Comment by peter-evans** [comment]
@menny I think you don't need to prefix with the org. The [API shows here](https://developer.github.com/v3/pulls/review_requests/#create-a-review-request) that it accepts "An array of team `slug`s that will be requested." The `slug` is the URL safe name of the team.

```
team-reviewers: owners, maintainers, languagemaintainers
```

**Comment by menny** [comment]
And teams can only be in the repo's organization?

**Comment by peter-evans** [comment]
I've not tested it, but the documentation for that API seems to suggest that it checks to see if a team is a collaborator of the repository. So presumably, if a team from another org has been added as a collaborator to the repository where the pull request is being created, it should work.

**Comment by menny** [comment]
seems to work as you described: https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/2089

Do you think this should be added to your docs?

**Comment by peter-evans** [comment]
I've updated the reference example here:
https://github.com/peter-evans/create-pull-request#reference-example

I didn't include that input on the reference example to start with because I just hadn't got around to testing it yet. Thanks for confirming how it works!

**Comment by menny** [comment]
Thank you for providing this project
