### ISSUE TITLE
updating an existing pull request branch is not working for me

### ISSUE THREAD

**Issue by jcable** [peter-evans/create-pull-request#1301]
### existing commits get orphaned

Firstly, this action is exactly what I need - as documented its absolutely perfect. Thanks for a great job.

What I'm seeing, is that if I make two successive changes to the same file, the first commit gets orphaned.

### What I expect

If my workflow gets triggered and there are no pending updates to this document, I expect the changed document to be committed to a new branch and a pr created.

The pr should consist of a single commit.

If my workflow gets triggered again with a second update to the same document, perhaps changing a different part of the document, I expect to see the first commit and the second commit in the pr.

### What I see

The first step works exactly as I expect.

After the second step I see only the second commit in the pr. The first commit has vanished.

If I have kept the first commit open on a browser tab, this commit can still be seen. But it now says:

"This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

### Steps to reproduce

1. run https://github.com/oldgaffers/boatregister/blob/main/.github/workflows/crud.yml
2. run the same workflow again with a different change to the same document.

Note, this workflow is passed a base64 encode of a json document representing the new document to be stored in the repository. This was because I was having problems passing the document in more directly. Currently the new document comes from an update to a row in a relational database but soon it will come from a web form.

**Comment by peter-evans** [comment]
Hi @jcable 

> If my workflow gets triggered again with a second update to the same document, perhaps changing a different part of the document, I expect to see the first commit and the second commit in the pr.

This is not how the action is designed to work. The "rule" that I based this action's design on is that when a workflow executes the action to create or update a PR, the result of those two possible paths should never be different. In other words, action runs are idempotent. This cannot be changed. It's fundamental to how the action works and is a conscious design decision.

So what you are seeing is correct. The action doesn't care about what currently exists in the PR branch, it looks at the current state of the local and base branches and recreates the PR that should exist to satisfy the conditions.

Hope that helps and you find this action useful.
