### ISSUE TITLE
action is not verified by gh

### ISSUE THREAD

**Issue by pharindoko** [peter-evans/create-pull-request#1305]
Hi 

### Subject of the issue

I`m getting an error trying to use github enterprise server and having a restriction to only use verified actions...

```bash
peter-evans/create-pull-request@v3 is not allowed to be used in xxx/testff3. Actions in this workflow must be: within a repository owned by uid10804, created by GitHub or verified in the GitHub Marketplace.
```

**Comment by peter-evans** [comment]
Hi @pharindoko 

Yes, this is not a verified action. As far as I know, only "partner organizations" of GitHub can have their actions verified. If you want to use this action you can either fork it to your own org, or allow access to unverified third-party actions.

You may find more info about how to configure GHE in the official documentation. I'm not familiar with it.

> GitHub Actions on GitHub Enterprise Server is designed to work in environments without full internet access. By default, workflows cannot use actions from GitHub.com and [GitHub Marketplace](https://github.com/marketplace?type=actions).

https://docs.github.com/en/enterprise-server@3.3/admin/github-actions/managing-access-to-actions-from-githubcom/about-using-actions-in-your-enterprise#about-actions-on-github-enterprise-server

**Comment by pharindoko** [comment]
Thanks for the hint @peter-evans.

My problem is that I want to use [projen](https://github.com/projen/projen) and they use your version in their update pipeline.
So I would have to modify this in two places and keep it up to date...

**Comment by peter-evans** [comment]
I see. That's an interesting problem. 🤔 

I've looked into becoming verified before, and it didn't seem like individuals that maintain third-party actions would qualify. I'll take a look at it again though.

I'm fairly sure that GitHub orgs (and perhaps config in GHE) allows you to configure specific actions that your org is allowed to use. That could be an option, and would be low risk because you could allow only this action.

**Comment by peter-evans** [comment]
Still seems there is no way for individuals to have actions verified. You need to join their partner program as an organization.

https://github.com/orgs/community/discussions/25265

**Comment by pharindoko** [comment]
Means you would have to move this to an organization first and then apply for the partner program ;)
Ok I guess I`ll try it first to talk to my ghe server admin to allow this specific action ...

**Comment by peter-evans** [comment]
> So I would have to modify this in two places and keep it up to date...

Another option would be to fork this action to your own org, then write a GitHub Actions workflow to automatically find `peter-evans/create-pull-request` and replace it with `my-org/create-pull-request`. You could even use the fork of this action to raise a pull request for the change. 😆

**Comment by pharindoko** [comment]
no ;)  Will let you know if I could convince my ghe admin and it works as expected...
