### ISSUE TITLE
Add option that allows to _not_ force push or to collect previous commit messages

### ISSUE THREAD

**Issue by ldb** [peter-evans/create-pull-request#1338]
### Subject of the issue

It would be great to have an option that allows the action to update existing PRs without force pushing to the branch. The use case is the following:
- I dispatch events in Repository A which are received in Repository B.
- Repository B then automatically creates or updates a PR with the contents of the dispatched event.
- One of these contents is the latest commit message in Repository A.
- I would like to collect all these commit messages in the PR so that they can be be the body of the single merge commit once the PR is being merged.

Right now, as new commits are force pushed to the PR branch, previous commit messages are being overwritten, by which I lose their messages.
By not force pushing all these messages could be collected when "Squashing and Merging" the PR.

Another solution could be to allow accessing the description of an existing PR. In that case one could use the description as a buffer that collects all previous messages and then simply amend any new messages. This should work even with force pushing.

Any feedback here would be greatly appreciated, thank you.

**Comment by peter-evans** [comment]
Hi @ldb 

Please see [this comment](https://github.com/peter-evans/create-pull-request/issues/1062#issuecomment-1044548704) for a bit of background about why the action behaves like this. At the moment I don't have any intention to change this behaviour.

> Another solution could be to allow accessing the description of an existing PR. In that case one could use the description as a buffer that collects all previous messages and then simply amend any new messages. This should work even with force pushing.

Sounds like this could work, but it's not something I want to add a specific feature for. I would suggest doing this in the workflow before this action is executed, and then just update the `body` input to whatever you have computed. You could fetch the existing body of the PR using [github-script](https://github.com/actions/github-script), for example.
