### ISSUE TITLE
V5 release timeline and outstanding work

### ISSUE THREAD

**Issue by codefish1** [peter-evans/create-pull-request#1463]
I can see v5 is upcoming and I was wondering on the timelines for this and what is outstanding which people could help with.

I'm keen for it since we need the fixed proxy support and the v4 with proxy support is unsuitable for our organisation due to the vulnerabilities which I know you've solved with v5-beta

**Comment by peter-evans** [comment]
Hi @codefish1 

There is nothing major outstanding, but I would like to hold off releasing it for a bit longer.

As I mentioned in [this comment](https://github.com/peter-evans/create-pull-request/issues/1267#issuecomment-1345974777), it's no problem to use the `v5-beta` branch of the action now. If it makes you feel more comfortable, I've created a `v5-rc` (release candidate) tag that you can use. I will keep the tag following the v5 branch and give you plenty of warning to update to `v5` after the release.

```yml
      - uses: peter-evans/create-pull-request@v5-rc
```
