### ISSUE TITLE
Question variables in lables

### ISSUE THREAD

**Issue by oluies** [peter-evans/create-pull-request#1485]
### Question variables in lables

I used a enveriment variable as a label and got an error , should it be possible? 

```
          labels: |
            "${{ env.IMG_BASENAME }}"
            argocd
            automated pr

```
### Steps to reproduce

Use an env variable in the PR creation

**Comment by peter-evans** [comment]
Hi @oluies 

Fairly sure this is possible. I don't think you need the quotes. Also, check that the variable actually has a value.
