### ISSUE TITLE
need more understanding on create pull request action 

### ISSUE THREAD

**Issue by vasagirisai** [peter-evans/create-pull-request#1486]
### Subject of the issue
while using the create pull request action i am getting both base and branch have no diff ... this is automatically merging from my feature branch to develop branch . can you plesae help me to get the best example
### Steps to reproduce

If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.

**Comment by peter-evans** [comment]
Hi @vasagirisai 

Please read the documention and examples:
https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md
https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md

If you can't figure out how to solve your problem from the documentation then please add more information about your use case and provide the workflow you are trying.

**Comment by vasagirisai** [comment]
Hello Peter
I am trying to create a PR after checking the ansible-lint on few yaml files from my feature branch .
this is my code 
name: ansible-lint

on: 
  push:
    branches: vasagirisai-patch-2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          ref: develop
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo python -m pip install ansible-lint
    - name: Run ansible-lint
      run: |
        ansible-lint *.yml
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: update master branch
        title: Update main branch
        branch: vasagirisai-patch-2
        reviewers: vasagirisai
        
        feature branch is vasagirisai-patch-2
        i want to create a pr to merge the changes after successful lint check .
        can you please help me with this ? Unable to understand, because it is showing no diff from base branch 
        can you please modify my code accordingly once ?Thanks
