### ISSUE TITLE
Add support for git:// remotes

### ISSUE THREAD

**Issue by eggyal** [peter-evans/create-pull-request#1489]
`create-pull-request` currently supports `http[s]://` and `git@` remotes:

https://github.com/peter-evans/create-pull-request/blob/84c5454c6e165b9ff002651085afb89402cd486a/src/utils.ts#L52-L56

However, the [`${{ github.repositoryUrl }}`](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) property is of the form `git://`.

**Comment by peter-evans** [comment]
Hi @eggyal 

What situation/setup do you have where the repo URL is in the form `git://`? Please could you share an example workflow. It would then help me to create a test for this feature.

**Comment by eggyal** [comment]
Sure, [this was my failing workflow](https://github.com/eggyal/copse/blob/e453e9aca0322b39cb346adaa5939d2da889ab91/.github/workflows/pull-upstream.yml#L66-L67) but It was [trivial](https://github.com/eggyal/copse/compare/e453e9aca0322b39cb346adaa5939d2da889ab91..e481ec102c660be315ba95b2f28b981fc8a9efc2) to change to HTTP so it was easily worked around.

In particular, I'm cheating a bit by running `create-pull-request` in a bare clone of a foreign repo, but was setting `origin` to `${{ github.repositoryUrl }}` so that the PR gets opened there.

This is so that PRs get opened in my repository to bring in upstream changes without having to checkout a copy of my repo (I must check out a copy of the upstream repo because I first do a `subtree split` on it).

**Comment by peter-evans** [comment]
For now, I think I'm happy with [this](https://github.com/eggyal/copse/compare/e453e9aca0322b39cb346adaa5939d2da889ab91..e481ec102c660be315ba95b2f28b981fc8a9efc2) being the workaround for the issue.

Copying the workaround here for reference:
```yml
        run: |
          git init --bare
          git config --local remote.origin.url '${{ github.server_url }}/${{ github.repository }}.git'
```

This action is designed to work with the official `actions/checkout` action. I've not come across any use cases where the official action cannot be used, but if they arise I'll reconsider supporting `git://` remotes if it helps. Thanks for raising the issue.
