### ISSUE TITLE
Use actions/checkout@v2 with `ssh` input

### ISSUE THREAD

**Issue by HenryNguyen5** [peter-evans/create-pull-request#150]
### Subject of the issue

The documentation suggests to manually clone an entire repository when wanting to use a deploy key.

https://github.com/actions/checkout now supports ssh checkout, so this should work fine without the `ssh-agent` and `git clone` steps right?

**Comment by peter-evans** [comment]
Hi @HenryNguyen5 

I tested the new `ssh-key` input of `actions/checkout` just now. It seems to work fine. 🎉 
Updated the [documentation here](https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#push-using-ssh-deploy-keys).

Thanks for the reminder.
