### ISSUE TITLE
pr is failing 

### ISSUE THREAD

**Issue by vasagirisai** [peter-evans/create-pull-request#1517]
Trying to create pull request with this code but failing with **Branch 'vasagirisai-patch-2' no longer differs from base branch 'develop'**
name: Create pull request
on:
  push:
    branches:
      - vasagirisai-patch-4

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Automatic pull request from feature branch"
        branch: develop
        base: vasagirisai-patch-4

**Comment by peter-evans** [comment]
Hi @vasagirisai 

This is the problem: `branch: develop`

The branch input should not be an existing branch. Please check the documentation and examples to give you an idea of how to use this action.
