### ISSUE TITLE
Pull Request creation 

### ISSUE THREAD

**Issue by vasagirisai** [peter-evans/create-pull-request#1518]
Hello Peter
I am trying to create a PR after checking the ansible-lint on few yaml files from my feature branch .
this is my code
name: ansible-lint

on:
push:
branches: vasagirisai-patch-2

jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3
with:
ref: develop
- name: Set up Python 3.7
uses: actions/setup-python@v2
with:
python-version: 3.7
- name: Install dependencies
run: |
sudo python -m pip install ansible-lint
- name: Run ansible-lint
run: |
ansible-lint *.yml
- name: Create Pull Request
uses: peter-evans/create-pull-request@v4
with:
commit-message: update master branch
title: Update main branch
branch: vasagirisai-patch-2
reviewers: vasagirisai

    feature branch is vasagirisai-patch-2
    i want to create a pr to merge the changes after successful lint check into develop 
    can you please help me with this ? Unable to understand, because it is showing no diff from base branch 
    can you please modify my code accordingly once ?Thanks

**Comment by peter-evans** [comment]
Hi @vasagirisai 

You are trying to trigger the workflow on push to `vasagirisai-patch-2`, but also use `vasagirisai-patch-2` as the `branch` input. This will not work.

This use case is quite tricky to get working well. Please see this section of the documentation which is about how to achieve this type of workflow:
https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#use-case-create-a-pull-request-to-modifyfix-pull-requests

**Comment by vasagirisai** [comment]
Hello Peter

Thanks for the response . But can you please modify my code as a example and so that i can take from there
