### ISSUE TITLE
New PR created with action does not contain signed commits

### ISSUE THREAD

**Issue by rcclemente** [peter-evans/create-pull-request#1607]
### Subject of the issue

Summary: We are currently enforcing a requirement that any commit must be signed. When we create a pull request with this action does not currently create signed commits even if the source of the commits are signed off. 

### Steps to reproduce

We are manually triggering this action to create pull request to our branches `test` -> `uat` 
All our commits to the base branch (test) are signed and merges to the base branch are created into releases/tagged.

We use this action to select the release we want to deploy. 

Is there a way that the created PR will have commits that will be gpg signed, somewhat inheriting from the original commit? 

### Screenshot

Commit
![Screen Shot 2023-02-09 at 14 32 03](https://user-images.githubusercontent.com/22880578/217736979-64dd2b45-36f4-40f8-bde7-02420e709809.jpg)

PR with signed commit
![Screen Shot 2023-02-09 at 14 40 45](https://user-images.githubusercontent.com/22880578/217737155-1cf15d6d-77c4-4775-8d17-dd51a6fe0808.jpg)

PR created from commit
![Screen Shot 2023-02-09 at 14 30 20](https://user-images.githubusercontent.com/22880578/217736909-f1e41dfb-8852-4671-ae0b-cc8175d4be02.jpg)

Thanks for the great project. It has been very useful for our workflow 🎆

**Comment by peter-evans** [comment]
Hi @rcclemente 

Thank you for sponsoring! ❤️ 

I've documented how to sign commits with GPG here:
https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#gpg-commit-signature-verification
