### ISSUE TITLE
add-paths is handled in a confusing way

### ISSUE THREAD

**Issue by laeubi** [peter-evans/create-pull-request#1665]
### Subject of the issue

I'm using a path spec to limit items added but it seems not working as described.

See the doc referenced in the file: https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec

Also the example on the page shows this:
```
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            *.java
            docs/*.md
```

### Steps to reproduce

The following patterns give strange results:

1. `pom.xml` only adds the file in the root but actually should match any file, if I understand the git docu correct, only matching the root must be written as `/pom.xml`
2. `**/pom.xml` only match subdirectories but NOT files in the root, if I understand correctly *any* file in any directory should be matched.

**Comment by peter-evans** [comment]
Hi @laeubi 

The action isn't doing anything special with this input. It's just passing it straight to git.

You can test locally first and see how git behaves:
```
git add 'pom.xml'
```

Note that you might need quotes in your terminal, but you don't need quotes when configuring the action input.

**Comment by laeubi** [comment]
@peter-evans thanks for the explanation, than it seems the action can't do anything and it might be "normal" behavior, maybe you still want to enhance the doc to make clear that this is effectively `git add <add-path>` ?

**Comment by peter-evans** [comment]
@laeubi I think the current wording is quite clear that it follows git's pathspec syntax. The misunderstanding here seems to be with interpreting Git's [pathspec documentation](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec), not this action's.

> Paths should follow git's pathspec syntax.

https://github.com/peter-evans/create-pull-request/blob/main/action.yml#L14

I'm going to leave it as-is for now, but I'll consider making changes in future if other users have similar queries about it's behaviour.
