### ISSUE TITLE
Milestone Format

### ISSUE THREAD

**Issue by torresmi** [peter-evans/create-pull-request#170]
### Supporting Non-Int Milestones

I'm using this action and would love to specify a Milestone. It looks like only int-based milestones are supported, as I am receiving this error. 

```
  File "/home/runner/work/_actions/peter-evans/create-pull-request/v2.7.0/dist/cpr/create_or_update_pull_request.py", line 127, in create_or_update_pull_request
    milestone = github_repo.get_milestone(int(milestone))
ValueError: invalid literal for int() with base 10: 'v4.9.13'
```

Any thoughts on supporting Milestones as Strings?
### Steps to reproduce
- Provide a non-int value for `milestone:` key

**Comment by peter-evans** [comment]
Hi @torresmi 

All milestones have a number. You can see the number in the URL.

![image](https://user-images.githubusercontent.com/18365890/80779214-f08f2880-8ba5-11ea-8a2f-779ebb89b7eb.png)

I don't think there is another way to reference milestones uniquely. GitHub only provides an API to fetch by number.
https://developer.github.com/v3/issues/milestones/#get-a-single-milestone

**Comment by torresmi** [comment]
Ah I see! Thanks!

**Comment by joshuacwnewton** [comment]
Sorry to necrobump this issue, and this of course isn't a high priority request or anything like that, but:

> I don't think there is another way to reference milestones uniquely. GitHub only provides an API to fetch by number.
> https://developer.github.com/v3/issues/milestones/#get-a-single-milestone

One way that I've found to work around this is to make a [request for a list of milestones](https://docs.github.com/en/rest/issues/milestones?apiVersion=2022-11-28#list-milestones), and then perform [string matching against the open milestones](https://github.com/neuropoly/changelog/blob/4890ec2a1d06c66f7a52f6b0b5d39aa516460d99/changelog/changelog.py#L85-L116). 

I believe title-matching does guarantee uniqueness? As GitHub will prevent you from creating multiple milestones with the same title:

![image](https://github.com/peter-evans/create-pull-request/assets/16181459/3df992f9-2786-44bb-a5d8-5292d879764c)

So, if there were a new input `milestone_title`, distinct from `milestone` (number), then maybe it would be possible to support both types of input.

**Comment by peter-evans** [comment]
> One way that I've found to work around this is to make a [request for a list of milestones](https://docs.github.com/en/rest/issues/milestones?apiVersion=2022-11-28#list-milestones), and then perform [string matching against the open milestones](https://github.com/neuropoly/changelog/blob/4890ec2a1d06c66f7a52f6b0b5d39aa516460d99/changelog/changelog.py#L85-L116).

Good to know that works, thanks. I don't think I'll add a `milestone_title` input, though. I try to keep the interface for this action to a minimum so it doesn't get bloated and complicated. If users have a use case where for some reason they have no access to the number and only the title, then my suggestion would be to do what you have described in a workflow step before the action runs to find the number. It could be done relatively easily with something like [github-script](https://github.com/actions/github-script).
