### ISSUE TITLE
GitHub App refuses to update or create CI workflows files without the `workflow` permission

### ISSUE THREAD

**Issue by frouioui** [peter-evans/create-pull-request#1713]
### Subject of the issue

Hello 👋🏻 

I have created a small tool that automatically updates a bunch of files and create a PR using your app. However, when changing GitHub Actions workflow files, GitHub complains with the following error:

```
refusing to allow a GitHub App to create or update workflow `.github/workflows/check_make_vtadmin_authz_testgen.yml` without `workflows` permission
```

### Steps to reproduce

See the entire failing workflow here: https://github.com/vitessio/vitess/actions/runs/4372158950/jobs/7648752751

**Comment by peter-evans** [comment]
Hi @frouioui 

This is normal behaviour for GitHub's permissions model. If you want to allow changes to the `.github/workflows` directory then you need to use a [PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) and give it the `workflows` scope in additional to `repo`.

**Comment by frouioui** [comment]
Hey @peter-evans, awesome, thank you!
