### ISSUE TITLE
Problem with committer field - it doesn't seem to work as expected

### ISSUE THREAD

**Issue by wiktor2200** [peter-evans/create-pull-request#1715]
Hello @peter-evans and contributors! Thanks for your great feature for Github Actions!

### Subject of the issue
I have a problem with setting `committer` field for scheduled pipeline. Pipeline is always triggered by `github-actions[bot]`, even though I'm setting other users `dependabot[bot]` in this case. I was trying with both `support@github.com` email with is used in signoff and also specific one used per project.

### Steps to reproduce
At first I've tried to introduce author and committer in this PR: https://github.com/nextcloud/ansible-collection-nextcloud-admin/pull/220/files 
after this change it was triggered by `github-actions` and commit by `dependabot` but not ours, some generic not existent user.
https://github.com/nextcloud/ansible-collection-nextcloud-admin/pull/223
https://github.com/nextcloud/ansible-collection-nextcloud-admin/pull/229

So I've fixed it there: https://github.com/nextcloud/ansible-collection-nextcloud-admin/pull/230/files
But it only fixed commit by `dependabot` which is now created by existing user, but still action is triggered by `github-action`.
https://github.com/nextcloud/ansible-collection-nextcloud-admin/pull/231

Do you have any idea, why `committer` is not applied by Github Action? Have you experienced this issue before?

**Comment by peter-evans** [comment]
Hi @wiktor2200 

The `author` and `committer` inputs are for the Git commit. They are unrelated to the GitHub user that creates the PR. If you use the default `GITHUB_TOKEN` then a special GitHub bot user creates the PR. That's why it's triggered by `github-actions[bot]`. If you want the PR creation and subsequent triggers to be a specific user then you need to use a PAT created on that user.

**Comment by wiktor2200** [comment]
Hi @peter-evans! Thanks a lot for your answer. 
I'll try setting PAT for specific user and see. I'll contribute to your README mentioning that, when confirmed and if you don't mind.
