### ISSUE TITLE
Getting Dependabot alert 

### ISSUE THREAD

**Issue by manoj27730** [peter-evans/create-pull-request#1717]
### Getting Dependabot alert 

Hi Team / @peter-evans 

I am trying to enable this below actions for my enterprise GitHub repository.

- name: Create Pull Request
  uses: peter-evans/create-pull-request@v4.2.3

But our Enterprise GitHub Team is unable to add the actions due to Dependabot alert.
Can you please help to fix the vulnerabilities and release new version or fix in the same version so that we can use them.

Thanks,
Manoj Kumar Sahu

**Comment by manoj27730** [comment]
<img width="642" alt="Dependabot error" src="https://user-images.githubusercontent.com/24359931/224937373-6607ce1c-a40d-49dd-9e71-e2b6a577944a.PNG">

**Comment by peter-evans** [comment]
Hi @manoj27730 

Those issues were fixed on `main` but I hadn't released a new version of the action. Apologies for that.

I've released `v4.2.4` / `v4`, which should contain the fixes.

**Comment by manoj27730** [comment]
> Hi @manoj27730
> 
> Those issues were fixed on `main` but I hadn't released a new version of the action. Apologies for that.
> 
> I've released `v4.2.4` / `v4`, which should contain the fixes.

Thank you
