### ISSUE TITLE
Validation Failed: {"resource":"PullRequest","field":"head","code":"invalid"}

### ISSUE THREAD

**Issue by littleGnAl** [peter-evans/create-pull-request#1763]
I'm not very sure if it's the same issue https://github.com/peter-evans/create-pull-request/issues/1459, here's my failed job:
https://github.com/littleGnAl/hoe/actions/runs/4492290785

After I change it to the restful API, it works fine:
https://github.com/littleGnAl/hoe/actions/runs/4492523688

**Comment by peter-evans** [comment]
Hi @littleGnAl 

It looks like you are trying to create a pull request from `AgoraIO/Agora-Flutter-SDK` to `AgoraIO-Extensions/Agora-Flutter-SDK`. In that case, you are checking out the wrong repository. You need to checkout the base of the pull request, that's `AgoraIO-Extensions/Agora-Flutter-SDK`, then you update the local repository from `AgoraIO/Agora-Flutter-SDK`. Then the action runs and will push to the correct repository.

The tricky part is updating from `AgoraIO/Agora-Flutter-SDK`. The simplest way is probably to checkout on a different path. Make sure the `path` input on the action points to the base repository, not the source of your updates.

**Comment by littleGnAl** [comment]
Thank you so much, @peter-evans , I change the repo to `AgoraIO-Extensions/Agora-Flutter-SDK`, and works fine now, sorry for my stupid mistake.
