### ISSUE TITLE
Action fails to create a PR

### ISSUE THREAD

**Issue by lfgcampos** [peter-evans/create-pull-request#1838]
### Subject of the issue

The action fails to create a PR.
I can share the repo is big and has several files.
In the image you can see it fails after ~15 minutes, which might be a hard limit on github itself.

![error-pr](https://user-images.githubusercontent.com/8443274/231130623-0f890ec5-bc77-484f-bbdc-d3e0bb492e9a.png)

If that is indeed a hard limit, is there anything else we can do to avoid it? =)

### Steps to reproduce

I would say any action taking more than 15 mins should be able to reproduce it.

**Comment by peter-evans** [comment]
Hi @lfgcampos 

I've never seen this error before. Are you saying that you have several very large files?

Are you using [Git LFS](https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage)? This action supports repositories using Git LFS, so that would be the best way to handle large files.

**Comment by lfgcampos** [comment]
Hi @peter-evans, thanks for the comment.

No, this repo actually has several files!
Not big but a lot of small ones.

This is not LFS as well.
I can provide more info if needed, just let me know.

KR,

**Comment by peter-evans** [comment]
@lfgcampos If possible can you share your workflow and more detail about the repo. There's not enough for me to understand how to reproduce this.

**Comment by lfgcampos** [comment]
Hi @peter-evans, sure.

It is a ~8GB repository mostly with images.
There should be around 100k images there.

In my action, I am piping a [compress image action](https://github.com/calibreapp/image-actions) and this create-pull-request one.

As you can see, it is a big repo but made out of several small files (images in this case).

There is nothing special on the action itself, it is pretty much the same as the example on the image-actions repo.

KR,

**Comment by peter-evans** [comment]
@lfgcampos I noticed that the example workflows for that action are using `v3` of this action. Please update to `v5`, just in case that fixes the issue.

Is the workflow trying to compress all 100k images and make a pull request for 100k changes? If that's the case, I'm not surprised if GitHub can't handle that. You might need to find a way to do the workflow in batches.

**Comment by lfgcampos** [comment]
@peter-evans, my workflow is using latest (`v5`).

This a 'full run' for making it more clear how it looks (check the times, it is a long workflow).

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/8443274/231997641-103a4379-c03d-43ee-b442-f590f53ece7d.png">


So, the compression works for all the files - not all of the 100k are compressed but a big chunk yes.

I agree with you that doing in batches is the way to go and once most of them are compressed, it won't happen again... it is more like a "1-of" thing.
But anyway, maybe there is something to be done and improved in general - and that's why I've decided to open the issue.

KR,

**Comment by peter-evans** [comment]
> But anyway, maybe there is something to be done and improved in general - and that's why I've decided to open the issue.

Got it. Unfortunately, I don't think there is a lot the action can do in this case. The error looks like it's coming from GitHub's side of the git protocol. My guess is that you have reached the limits of what GitHub allow for `git push`. I don't know, but [Git LFS](https://docs.github.com/en/repositories/working-with-files/managing-large-files) might help in this situation even though you are dealing with lots of small files.

Thanks for creating the issue, though. It's good to know about this limitation. 👍
