### ISSUE TITLE
Feature request: disable force updates to existing branches/PRs

### ISSUE THREAD

**Issue by Sophie1142** [peter-evans/create-pull-request#1871]
### Subject of the issue

It'd be incredibly helpful if the action had a parameter to configure whether or not existing branches/PRs should be `force-pushed`. I'm writing a composite action that calls this action, and just discovered that if the action force-pushes it overrides all pre-existing commits on that PR. 

Thanks so much for your time and consideration!

### Steps to reproduce

If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.

**Comment by peter-evans** [comment]
Hi @Sophie1142 

This behaviour is fundamental to how the action works and is a conscious design decision. The "rule" that I based this design on is that when a workflow executes the action to create or update a PR, the result of those two possible actions should never be different. The easiest way to maintain that consistency is to rebase the PR branch and force push it.

If you want to avoid this behaviour there are some things that might work depending on your use case:
- Check if the pull request branch exists in a separate step before the action runs and act accordingly.
- Use the [alternative strategy](https://github.com/peter-evans/create-pull-request#alternative-strategy---always-create-a-new-pull-request-branch) of always creating a new PR that won't be updated by the action.
- [Create your own commits](https://github.com/peter-evans/create-pull-request#create-your-own-commits) each time the action is created/updated.

If you need further help specific to your use case then feel free to provide detail.
