### ISSUE TITLE
Error: Not Found after trying to create a PR

### ISSUE THREAD

**Issue by georgius17** [peter-evans/create-pull-request#1872]
### Subject of the issue

Hi, please I would be very thankful for any help. I am trying to implement an auto-synchronize for a forked private repo. Original repo (lets call it _repo-orig/fe_) has the branch "dev" and when the "push" occurs I want to create a pull request to the forked repo (_repo-forked/app-fe_) to the branch "develop". Both repos are private. 

Below is my current solution (placed in _repo-orig/fe_):
`name: Auto PR to repo-forked/app-fe

on:
  push:
    branches:
      - dev

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:

      - name: SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout repo-forked/app-fe
        uses: actions/checkout@v3
        with:
          repository: repo-forked/app-fe
          ref: develop 
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Reset master branch
        run: |
          git remote add upstream https://github.com/repo-orig/fe.git
          git fetch upstream dev:dev
          git reset --hard dev
      
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        id: cpr
        with:
          title: Automatic PR from repo-orig/fe
          commit-message: Automatically generated pull request
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: dev
          labels: |
            update
          draft: false
          body: |
            Automatic pull request from repo-orig/fe to repo-forked/app-fe`

All of the steps works fine except for the last one - creating a pull request. Here is the log fragment:

"
 remote: Resolving deltas: 100% (6017/6017), completed with 245 local objects.        
 remote: 
 remote: Create a pull request for 'dev' on GitHub by visiting:        
 remote:      https://github.com/repo-forked/app-fe/pull/new/dev   
 remote: 
 To github.com:repo-forked/app-fe.git
 [new branch]      dev -> dev
 Create or update the pull request
 Attempting creation of pull request
 Error: Not Found
"

The branch "dev" is created in the forked-repo and contains the relevant code/commits, but thats all.

### Steps to reproduce

Since the repo is private I cannot add a link here, but I could post a link to the full downloaded log if it helps.

**Comment by peter-evans** [comment]
Hi @georgius17 

This is a permissions issue. Using an SSH key you have given the action permission to push to the repository using the git protocol, but because you are trying to create a pull request in a remote repository the action doesn't have permission using the default `GITHUB_TOKEN` set in the `token` input. This limitation of SSH keys is mentioned in the docs.

> Note that you cannot use deploy keys alone to [create a pull request in a remote repository](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#creating-pull-requests-in-a-remote-repository) because then using a PAT would become a requirement. This method only makes sense if creating a pull request in the repository where the workflow is running.

https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#push-using-ssh-deploy-keys

To fix this you have two options:
1. Run the workflow in the repository where you want to create the pull request. Then the default `GITHUB_TOKEN` will have permission to create it.
2. Use a PAT instead of an SSH key

**Comment by georgius17** [comment]
Thank you very much for the help and quick answer. I have added the PAT and the action now completes successfully.
