### ISSUE TITLE
Update to v5 fails with permission denied on push

### ISSUE THREAD

**Issue by jrfnl** [peter-evans/create-pull-request#1873]
### Background of the workflow

The workflow in which the action runner is used:
* In job 1, generates some files (project documentation) and uploads that to an artifact.
* Then in job 2:
    - checks out the `gh-pages` branch
    - downloads the artifact
    - puts a subset of the documentation files in their correct place in the `gh-pages` branch
    - will commit this subset.
    - puts the rest of the documentation files in the right place in the `gh-pages` branch
    - triggers the `create-pull-request` action runner to commit the second set of files and create the PR.
    - does a test build to ensure the GH Pages site will build correctly based on the changes in the PR

The workflow runs whenever a new tag is created.

The workflow also does a "dry-run" whenever the workflow or any of the files used in the workflow to generate the PR is changed and should create a "draft" PR as the result of the "dry-run".

 
### Problem 1

We recently received the @dependabot PR to update to `v5` of this action runner and the (dry-run of the) workflow for that PR is failing with the following error.

```
Pushing pull request branch to 'origin/feature/auto-ghpages-update-804/merge'
  /usr/bin/git push --force-with-lease origin feature/auto-ghpages-update-804/merge:refs/heads/feature/auto-ghpages-update-804/merge
  remote: Permission to WordPress/Requests.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/WordPress/Requests/': The requested URL returned error: 403
  Error: The process '/usr/bin/git' failed with exit code 128
```

### Problem 2

>     - does a test build to ensure the GH Pages site will build correctly

With the change in `v5` to switch back to the original branch, the last step in our workflow would not work correctly as in that case, it will do the test build on the original `gh-pages` branch (which has already been deployed) and not on the new branch which contains the changes for which we need to verify that the site will build correctly with those changes included....

I suppose, I could add an additional step to check out the newly created branch (again) before running the test build, but that feels very counter-intuitive.

## Steps to reproduce

Dependabot PR to update the action runner: https://github.com/WordPress/Requests/pull/804
Workflow file: https://github.com/WordPress/Requests/blob/develop/.github/workflows/update-website.yml
Logs of the failing build: https://github.com/WordPress/Requests/actions/runs/4656066685/jobs/8306015865 (and yes, I have re-run it to ensure it wasn't a hickup on GitHub)

For reference, with `v4` everything worked correctly. Here are some previously (and successfully) created PRs from this workflow:
* GH Pages site update on tag (last week): https://github.com/WordPress/Requests/pull/799 and the workflow logs for that run: https://github.com/WordPress/Requests/actions/runs/4606010534
* A previous dry-run: https://github.com/WordPress/Requests/pull/787 and the workflow logs for that run: https://github.com/WordPress/Requests/actions/runs/3741307915

**Comment by peter-evans** [comment]
Hi @jrfnl 

For problem 1, it looks like you aren't setting the `token` input on the action and therefore using the default `GITHUB_TOKEN`. When dependabot triggers a PR the `GITHUB_TOKEN` is read-only and you must explicitly give it write permissions. (See docs [here](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions))

Add this section to your workflow to give the default `GITHUB_TOKEN` write permissions.
```yml
permissions:
  pull-requests: write
  contents: write
```
See an example [here](https://github.com/peter-evans/create-pull-request/blob/main/.github/workflows/ci.yml#L14-L16).

As for problem 2,

> I suppose, I could add an additional step to check out the newly created branch (again) before running the test build, but that feels very counter-intuitive.

Yes, this is exactly what you should do. Apologies for the change, but I think it's more correct for the action to leave the environment as close to way it was when the action started as possible. This new behaviour also unlocks some other use cases that I wanted to support.

**Comment by jrfnl** [comment]
Hi @peter-evans, thanks for getting back to me.
 
> For problem 1, it looks like you aren't setting the `token` input on the action and therefore using the default `GITHUB_TOKEN`. When dependabot triggers a PR the `GITHUB_TOKEN` is read-only and you must explicitly give it write permissions. (See docs [here](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions))

Ah! That explains it. We probably never had a dependabot PR for this workflow before, so until now, this was never a problem.

Thank you for pointing out the underlying reason for the build failure!

> > I suppose, I could add an additional step to check out the newly created branch (again) before running the test build, but that feels very counter-intuitive.
> 
> Yes, this is exactly what you should do. Apologies for the change, but I think it's more correct for the action to leave the environment as close to way it was when the action started as possible.

No need to apologize, I just wanted to make sure I understood correctly how to handle this change.

I've opened a PR to fix the workflow and will rebase the Dependabot PR after my PR has been merged. I'm going to presume it will all work as expected again by then, so I'll close this issue. If things are still wonky after the Dependabot PR rebase, I'll re-open or open a new issue.

Thanks for your help!
