### ISSUE TITLE
fatal: could not read Username for 'https://github.com/': No such device or address

### ISSUE THREAD

**Issue by nvuillam** [peter-evans/create-pull-request#2094]
### Subject of the issue

Since a few days, my automated job is unable to create new PR using create-pull-request Github Action

The error is the following:

```sh
Checking the base repository state
  /usr/bin/git symbolic-ref HEAD --short
  main
  Working base is branch 'main'
  /usr/bin/git remote prune origin
  fatal: could not read Username for 'https://github.com/': No such device or address
  Error: The process '/usr/bin/git' failed with exit code 128
```

![image](https://github.com/peter-evans/create-pull-request/assets/17500430/182c289c-1f39-4e10-99f8-10042d7d7518)

### Steps to reproduce

You can have a look at the issue in its natural habitat here -> https://github.com/oxsecurity/megalinter/actions/runs/5317239991/jobs/9627563790

The workflow is the following and has not been updated for a while -> https://github.com/oxsecurity/megalinter/blob/main/.github/workflows/auto-update-linters.yml

Many thanks for your support :)

**Comment by peter-evans** [comment]
Hi @nvuillam 

This usually occurs when there is a problem with the token. Please could you check the following issues to see if they help you resolve it.

- https://github.com/peter-evans/create-pull-request/issues/1300
- https://github.com/peter-evans/create-pull-request/issues/871

**Comment by nvuillam** [comment]
@peter-evans many thanks for your quick reply :)

I thought my token was ok, but I regenerated a new one to check

I'll close the issue once I confirm it's ok :)

**Comment by nvuillam** [comment]
It was indeed a token issue, thanks again for your quick reply :)
