### ISSUE TITLE
Is there a way to Create a PR in a different repository ? 

### ISSUE THREAD

**Issue by arununzer** [peter-evans/create-pull-request#2099]
### Subject of the issue
Is there a way to Create a PR in a different repository ? 
Describe your issue here.
I am trying to create a PR in reusable workflow repository 
### Steps to reproduce
I am trying to create a PR in reusable workflow repository . Need to know if there is A way to create a repository in another repo From the current repo.

If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.

**Comment by peter-evans** [comment]
Hi @arununzer 

Yes. Please see https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#creating-pull-requests-in-a-remote-repository
