### ISSUE TITLE
No commits between master and ...

### ISSUE THREAD

**Issue by Atry** [peter-evans/create-pull-request#2105]
### Subject of the issue

```
  Error: Validation Failed: {"resource":"PullRequest","code":"custom","message":"No commits between master and update/master/scala-project-template"}
```

### Steps to reproduce

- [error log](https://github.com/ThoughtWorksInc/bindable.scala/actions/runs/5435389424/jobs/9884460382)
- [workflow](https://github.com/ThoughtWorksInc/bindable.scala/actions/runs/5435389424/workflow)

**Comment by peter-evans** [comment]
Hi @Atry 

I'm not sure what you are trying to do on these lines:
https://github.com/ThoughtWorksInc/bindable.scala/actions/runs/5435389424/workflow#L23-L24

It looks like you are trying to copy code from a remote repo to a directory in the current repo? I recommend just using the checkout action a second time to fetch the template to `path: template`. Then copy the files to where you want them to be in the current repo.

**Comment by peter-evans** [comment]
Perhaps take a look at this workflow to see if it helps you. It's a similar use case.
https://github.com/peter-evans/swagger-github-pages/blob/master/.github/workflows/update-swagger.yml

**Comment by Atry** [comment]
Thank you. I use `git reset` because sometimes `ThoughtWorksInc/bindable.scala` and `Atry/scala-project-template` change the same file and it can result in conflicts. If I use `cp`, it would override the changes made by `ThoughtWorksInc/bindable.scala`.
