### ISSUE TITLE
Error when running this action from an EC2 hosted runner

### ISSUE THREAD

**Issue by john-jerome** [peter-evans/create-pull-request#2181]
### Subject of the issue

I'm trying to run this actions on an EC2 hosted runner and I'm getting the following error:

```bash
Prepare git configuration
/usr/bin/git config --global --name-only --get-regexp safe.directory /actions-runner/_work/dbt-source-layer/dbt-source-layer
fatal: $HOME not set
/usr/bin/git config --global --add safe.directory /actions-runner/_work/dbt-source-layer/dbt-source-layer
fatal: $HOME not set
Error: The process '/usr/bin/git' failed with exit code 128
```

I'm using a PAT with all the necessary scopes on the repo.

![Screenshot 2023-07-31 at 11 46 08](https://github.com/peter-evans/create-pull-request/assets/31763328/eb7bf720-4345-48d7-9013-246019e42170)

Am I doing something wrong?
Thanks!

**Comment by peter-evans** [comment]
Hi @john-jerome 

This explanation might be the same problem: https://stackoverflow.com/a/56957868/11934042

The solution described won't work in this case. I think you need to run the EC2 instance as a user, not root. The root user doesn't have a $HOME directory, according to the blog post linked in that answer.

**Comment by peter-evans** [comment]
Closing this for now.
