### ISSUE TITLE
feature request: add output to signal if a pr is actually created

### ISSUE THREAD

**Issue by 0rphee** [peter-evans/create-pull-request#2267]
### Add output with status of the created pr

If we already have this outputs:

    pull-request-number - The pull request number.
    pull-request-url - The URL of the pull request.
    pull-request-operation - The pull request operation performed by the action, created, updated or closed.
    pull-request-head-sha - The commit SHA of the pull request branch.

Why not another: `pull-request-created` - true, it was created, false, it wasn't (there wasn't anything to commit)

Thanks for the great action!

**Comment by peter-evans** [comment]
Hi @0rphee 

For that case I think you can just check `pull-request-operation`. If it's empty then the action did nothing.
