### ISSUE TITLE
Request: Document PAT permissions requirements for machine accounts

### ISSUE THREAD

**Issue by joshlf** [peter-evans/create-pull-request#2387]
I'm following the steps described [here](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#push-pull-request-branches-to-a-fork) using [this machine account](https://github.com/google-pr-creation-bot) to submit PRs to [zerocopy](https://github.com/google/zerocopy). My current attempt is [here](https://github.com/google/zerocopy/pull/408), with the latest GitHub Actions failure [here](https://github.com/google/zerocopy/actions/runs/6281053435/job/17058994255?pr=408).

It'd be awesome if those docs could explain what permissions a PAT needs in order for this flow to succeed. I'm not positive, but my guess is that I'm not granting the PAT the right permissions in this case, which is the cause of the failure.

**Comment by peter-evans** [comment]
Hi @joshlf 

I think what you are experiencing is the same as this issue: https://github.com/peter-evans/create-pull-request/issues/1791

I guess you are trying to use a fine grained access token. They are still in beta and don't work for all GitHub APIs yet. Please use a classic PAT with `repo` scope, as described in the above linked issue. You also need 'workflow' scope if the generated PR will ever contain changes to the `.github/workflows` directory.

**Comment by joshlf** [comment]
That worked perfectly, thanks for the help!
