### ISSUE TITLE
add a no-verify option

### ISSUE THREAD

**Issue by xenoterracide** [peter-evans/create-pull-request#2413]
my git hooks won't/don't need to work in CI, I don't see a way to disable with this, can you please add the option to use `--no-verify`

**Comment by peter-evans** [comment]
Hi @xenoterracide 

Please see this post for solutions.
https://github.com/peter-evans/create-pull-request/pull/1875#issuecomment-1521008361

If these solutions don't work for your case then please provide your workflow any further detail.
