### ISSUE TITLE
Upgrade action to use node20

### ISSUE THREAD

**Issue by erikburt** [peter-evans/create-pull-request#2444]
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

> Node 16 has reached its [end of life](https://github.com/nodejs/Release/#end-of-life-releases), prompting us to initiate its deprecation process for GitHub Actions. Our plan is to transition all actions to run on Node 20 by Spring 2024. We will actively monitor the migration's progress and gather community feedback before finalizing the transition date. Starting October 23rd, workflows containing actions running on Node 16 will display a warning to alert users about the upcoming migration.
> ## What you need to do
> ### For Actions maintainers
> Modify your actions to run on Node 20 instead of Node 16. For guidance, refer to the [Actions configuration settings ](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions).

**Comment by peter-evans** [comment]
Hi @erikburt 

Please see https://github.com/peter-evans/create-pull-request/pull/2340

The upgrade to Node 20 is merged to the v6 release candidate. You can use it like this:

```yml
      - uses: peter-evans/create-pull-request@v6-rc
```

I'll be releasing `v6` at some point in the near future.

**Comment by brianeclow** [comment]
What is the status of cutting the next major version?

**Comment by peter-evans** [comment]
I'm planning to release it next week.

I was holding off as long as possible because last time I bumped Node (12 -> 16) a lot of users on GitHub Enterprise were caught out. However, it seems the runner has recently started warning that node16 as deprecated, so I think I'll go ahead with this release now.

**Comment by peter-evans** [comment]
I've now released `v6`. Thanks for your patience.

**Comment by imzedi** [comment]
will it work with node 22?

**Comment by HarelM** [comment]
@peter-evans github has a warning now for node 20, would you be able to update this action to use a newer version of node?

<img width="1697" height="202" alt="Image" src="https://github.com/user-attachments/assets/5fd1cced-5122-496c-b4cd-6cf06e980a23" />

Thanks for this great action BTW!

**Comment by peter-evans** [comment]
Hi @HarelM 

The latest version of the action is now on node24. Please upgrade to remove this warning.
https://github.com/peter-evans/create-pull-request/blob/eec7ab75b2f71ddc8a223341c83a67f6f774c39f/action.yml#L97

**Comment by HarelM** [comment]
Ok, thanks for the quick response! I'll check why dependabot did not update this.
