### ISSUE TITLE
Github Action is not working

### ISSUE THREAD

**Issue by ninjadev0831** [peter-evans/create-pull-request#2522]
This is yaml config.

- name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ env.GITHUB_TOKEN }}
          title: "Merge master into staging"
          commit-message: "Merge commit message"
          branch: staging
          base: master

This is not working now
I can't merge master to staging branch.

**Comment by peter-evans** [comment]
Hi @ninjadev0831 

For this case, please follow this example: https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another
