### ISSUE TITLE
using with git-crypt

### ISSUE THREAD

**Issue by Borda** [peter-evans/create-pull-request#2529]
### Subject of the issue

We have repo encrypted so at the beginning of the job we decrypt it with:
```yaml
  - name: Unlock secrets
    uses: sliteteam/github-action-git-crypt-unlock@1.2.0
    env:
      GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT }}
```
but then the create PR still fails with:
```
Create or update the pull request branch
  /usr/bin/git symbolic-ref HEAD --short
  main
  Working base is branch 'main'
  /usr/bin/git checkout --progress -B b41f56e3-3011-4bcc-87b5-c2b4fc1518bf HEAD --
  git-crypt: Error: Unable to open key file - have you unlocked/initialized this repository yet?
  error: external filter '"git-crypt" clean' failed 1
  error: external filter '"git-crypt" clean' failed
  fatal: kubernetes/prod/values.yml: clean filter 'git-crypt' failed
  Error: The process '/usr/bin/git' failed with exit code 128
```

**Comment by Borda** [comment]
for some reason, replacing the `sliteteam/github-action-git-crypt-unlock@1.2.0`
with just running the code for un-crypt helped:
```yaml
  - run: |
      sudo apt-get update -q
      sudo apt-get install -y git-crypt
      git config --global --add safe.directory $(pwd)
      echo ${{ secrets.GIT_CRYPT }} | base64 --decode | git-crypt unlock /dev/stdin
```

**Comment by peter-evans** [comment]
Hi @Borda 

Good to see that you found a workaround.

Is it similar to this issue? https://github.com/sliteteam/github-action-git-crypt-unlock/issues/12
It could just be a bug of that action.

**Comment by Borda** [comment]
> Is it similar to this issue? [sliteteam/github-action-git-crypt-unlock#12](https://github.com/sliteteam/github-action-git-crypt-unlock/issues/12) It could just be a bug of that action.

Seems different as our solution stream the key and so tried with file and worked too...

**Comment by peter-evans** [comment]
I'll close this now because I don't think there is an issue with this action. Your workaround will be helpful to anyone searching for help. 👍
