### ISSUE TITLE
Add color to labels

### ISSUE THREAD

**Issue by pascalgulikers** [peter-evans/create-pull-request#2765]
### Subject of the issue

When adding (new) labels to a PR, I would like to specify the color of this label. Is that possible?

### Steps to reproduce

If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.

**Comment by peter-evans** [comment]
Hi @pascalgulikers 

It's not currently possible with this action. Technically, it might be possible to add the feature, but it would be an awkward interface and complicate the logic quite a bit. At the moment I think I would prefer to not include this feature.

As a workaround, you could execute a step after this action to change the color of labels. You want to execute [this API](https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#update-a-label), perhaps using [github-script](https://github.com/actions/github-script) action, or octokit's [request-action](https://github.com/octokit/request-action).
