### ISSUE TITLE
Change the authorship of pull requests

### ISSUE THREAD

**Issue by jobinjosem1** [peter-evans/create-pull-request#2779]
### Subject of the issue
Change the authorship of pull requests
Describe your issue here.

Generating a pull request with this action currently attributes the authorship to 'github-actions,' potentially leading to a situation where the initiating user can autonomously approve and merge it, posing a certain level of risk. Is there a way to designate the creator of the pull request as the individual who initiated the workflow, thereby necessitating review by another party before merging?
### Steps to reproduce

   - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update report
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: example-patches
          delete-branch: true
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: peter-evans
          reviewers: peter-evans
          team-reviewers: |
            developers
            qa-team
          milestone: 1
          draft: false

**Comment by peter-evans** [comment]
Hi @jobinjosem1 

The PR will always be created by the user account associated with the `token`. There is no way to change this. This is just how GitHub auth works. If you want to change the user, you must use a token (PAT) associated with that user.

Please see the docs here about different ways to supply a token.
https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs

As for approval controls. I recommend using GitHub's own features. You can turn on branch protection rules and force PRs to have approvals from a certain number of users, or `CODEOWNERS`, etc.
