### ISSUE TITLE
Action won't create pull request

### ISSUE THREAD

**Issue by cegekaJG** [peter-evans/create-pull-request#2807]
### Subject of the issue

I have a workflow that creates a new branch, cherry-picks a single commit and finally creates a pull request. Unfortunately, even though I can create a pull request manually, the action fails to do the same.

### Links

- [The workflow using the action](https://github.com/cegekaJG/test-branch-update/blob/e160a446c4a3c95f44e8fa9ae129f8656e828d72/.github/workflows/UpdateTestBranch.yaml#L202-L219)
- [The log of the most recent job](https://github.com/cegekaJG/test-branch-update/actions/runs/8168655850/job/22331210746) (See step "Finally: Create Pull Request")

### Steps to reproduce

You can fork [my repository](https://github.com/cegekaJG/test-branch-update) and try for yourself. Ensure your repo has the branch `testmaster` and create a new pull request with some change.

**Comment by peter-evans** [comment]
Hi @cegekaJG 

I think this is a misunderstanding about how this action works. Please see this section of the docs for help: https://github.com/peter-evans/create-pull-request/blob/main/docs/common-issues.md#create-using-an-existing-branch-as-the-pr-branch
