### ISSUE TITLE
Base parameter causes extremely slow checkout of our monorepo

### ISSUE THREAD

**Issue by webmonarch** [peter-evans/create-pull-request#2809]
### Long checkout when using `base` parameter on large repo

I am testing a GH action and using the `base` parameter. When using the base parameter, the create pull request step starts taking 18 mins (see screenshot). I am guessing it is running a full pull (instead of a shallow one or something similar).

### Steps to reproduce

Git command from logs:

`/usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --force origin develop:develop`

![image](https://github.com/peter-evans/create-pull-request/assets/471903/2575b910-7ee1-44d4-bcd5-59db63a08d10)

**Comment by peter-evans** [comment]
Hi @webmonarch 

You shouldn't need to use the `base` parameter unless the action can't work it out. The action defaults the `base` to the branch currently checked out. For some use cases, like being checked out on commit, it's necessary to let the action know what branch it should `base` the PR on. Unfortunately, using the `base` input causes another fetch, but it's unavoidable for those use cases.

If you show me your workflow I might be able to see if you can avoid using the `base` input.

**Comment by webmonarch** [comment]
@peter-evans in general, I shouldn't need to use the `base` parameter, but while in development, I am trying to create a PR against `develop` while my gh action is running on a `feature/branch`.
