### ISSUE TITLE
punycode module is deprecated

### ISSUE THREAD

**Issue by toobuntu** [peter-evans/create-pull-request#2822]
### Subject of the issue

```bash
(node:58522) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

### Steps to reproduce

This came up running a test workflow in [Act](https://github.com/nektos/act "https://github.com/nektos/act") on macOS 14.4 on arm64. I didn't necessarily expect create-pull-request to succeed using Act, but thought I'd share the deprecation warning in case it is more generally relevant. Feel free to close this issue if it is not.

```bash
act --platform macos-latest=-self-hosted -j update-workflow
```

See https://github.com/yarnpkg/yarn/issues/9005 and

https://nodejs.org/api/punycode.html
> The version of the punycode module bundled in Node.js is being deprecated. In a future major version of Node.js this module will be removed. Users currently depending on the punycode module should switch to using the userland-provided [Punycode.js](https://github.com/bestiejs/punycode.js) module instead. For punycode-based URL encoding, see [url.domainToASCII](https://nodejs.org/api/url.html#urldomaintoasciidomain) or, more generally, the [WHATWG URL API](https://nodejs.org/api/url.html#the-whatwg-url-api).

**Comment by peter-evans** [comment]
Hi @toobuntu 

I have no dependency on that module directly, it's indirect via other dependencies. Since I use dependabot to keep all dependencies up to date, I think that's enough to make sure this gets resolved as soon as my dependencies update.
