### ISSUE TITLE
Default to "Squash and Merge"

### ISSUE THREAD

**Issue by levb** [peter-evans/create-pull-request#2854]
### Subject of the issue

Is it possible to create PRs defaulting to "Squash and Merge"?

**Comment by peter-evans** [comment]
Hi @levb 

You can do this in your repository settings. Just uncheck the `merge` and `rebase` options:

![image](https://github.com/peter-evans/create-pull-request/assets/18365890/e81dbabd-f836-4cfd-9191-74a529e8953d)
