### ISSUE TITLE
`title-path` and `commit-message-path` inputs

### ISSUE THREAD

**Issue by iguessthislldo** [peter-evans/create-pull-request#2864]
I'd like to generate `commit-message`, `title`, and `body` in the script I'm using to make the PR changes and supply them to create-pull-request through files, but only `body` has an option for that. For right now I'm going to try committing manually with `git commit --file` and pass the title through an environment variable, but it would be nice if there was a `title-path` and `commit-message-path`.

**Comment by peter-evans** [comment]
Hi @iguessthislldo 

I won't be adding `-path` inputs for these. If you want to store that information in a file, that will work fine. You will just need a step before the action runs to read the contents of the file into a variable. Then use the variables to set the action inputs.

There's a snippet in the docs about dynamic config with variables, if it helps.
https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#dynamic-configuration-using-variables
