### ISSUE TITLE
ignore untracked

### ISSUE THREAD

**Issue by mbrevda** [peter-evans/create-pull-request#2883]
Is there any way to ignore untracked files? I.e. if there are changed _existing_ files commit them, but ignore any new files

**Comment by peter-evans** [comment]
Hi @mbrevda 

There is no option for this in the action, but I think you can just add a step before the action runs to remove untracked files. 

```yml
run: git clean -fd
```

**Comment by mbrevda** [comment]
thanks! Not perfect, but good enough.
