### ISSUE TITLE
Required checks are not being triggered after the PR creation

### ISSUE THREAD

**Issue by Pavaningithub** [peter-evans/create-pull-request#2912]
### Subject of the issue

Required checks are not being triggered after the PR creation

Describe your issue here.

When we manually create the PR, certain mandatory checks and workflows trigger. However, using this task prevents the checks from being initiated. Empty commits cause the triggering of those checks.

### Steps to reproduce

If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.

**Comment by peter-evans** [comment]
Hi @Pavaningithub 

There's a section in the docs about this. Please see here: https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
