### ISSUE TITLE
Node version - Warning

### ISSUE THREAD

**Issue by JuanPabloDiaz** [peter-evans/create-pull-request#2932]
### Subject of the issue
I am using it and I got the following warning:
[linkChecker](https://github.com/JuanPabloDiaz/LinksHub/actions/runs/9311619475/job/25631090631)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: peter-evans/create-pull-request@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Describe your issue here.
- I check the runs in `action.yml` file and notice that its using node20 but the warning shows 16. I am using `peter-evans/create-pull-request@v3`
```yml
runs:
  using: 'node20'
  main: 'dist/index.js'
```

Is there something else I need to do?

### Steps to reproduce

If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.

**Comment by peter-evans** [comment]
Hi @JuanPabloDiaz,

Please use the latest version of the action, `v6`.

```yml
peter-evans/create-pull-request@v6
```
