### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by hchauvat-owkin** [peter-evans/create-pull-request#2933]
### Subject of the issue

I'm new to this, so very sorry if this has been asked before. I have created a rather simple workflow that checks out my code, performs some Lokalise-based (and irrelevant) action and then tries to create a PR on said repo. I'm currently testing this workflow **locally** using `act` and when I reach that last step, and even though I'm providing a PAT with repo access (only) and authorized SSO, I get the following error:
```
[Sync with Lokalise/lokalise]   ❓  ::group::Checking the base repository state
| [command]/usr/bin/git symbolic-ref HEAD --short
| setup-locales-sync
| Working base is branch 'setup-locales-sync'
| [command]/usr/bin/git remote prune origin
| git@github.com: Permission denied (publickey).
| fatal: Could not read from remote repository.
| 
| Please make sure you have the correct access rights
| and the repository exists.
[Sync with Lokalise/lokalise]   ❗  ::error::The process '/usr/bin/git' failed with exit code 128
```
I did try passing the token directly to make sure it wasn't lost somewhere on the way, but no luck

### Steps to reproduce

Here's my [workflow](https://gist.github.com/hchauvat-owkin/4b4157a3f7cc30000c181078fe858c54)
The command I use to start everything is: 
```
act --secret-file ./.secrets
```
with .secrets containing all the aforementioned variables.

**Comment by hchauvat-owkin** [comment]
Nevermind, this issue didn't appear live on GitHub

**Comment by peter-evans** [comment]
Hi @nexstar-emorales 

I've never used act and have no idea if this action has ever worked with act. Unfortunately, I don't have a lot of time to invest in investigating, but if anyone has insights into why it doesn't work that could be helpful. Perhaps there are some minor things I could do to allow it to work, but I have no idea. 🤷 😄
