### ISSUE TITLE
PR still created with 0 files (no diffs)

### ISSUE THREAD

**Issue by caseybaggz** [peter-evans/create-pull-request#3006]
### Subject of the issue

The action is somehow still creating a PR that contains no changes

Describe your issue here.

In our use case, we are generating static files in the CI, then running the action. Looks like the logs track that there are differences via `git status` but no actual changes. Even in this scenario, the action still creates a PR.

[Buggy CI Job](https://github.com/omnifed/cerberus/actions/runs/9780821349/job/27003390432)

### Steps to reproduce

1. Create some json files in a repo
2. Create a CI job that writes to those JSON files of the same content
3. Run the action
4. See the (empty) PR created

If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.

https://github.com/omnifed/cerberus/actions/runs/9780821349/job/27003390432

**Comment by peter-evans** [comment]
Hi @caseybaggz 

I'm not 100% sure what's happening, but my guess is that the initial diff (of 7 json files) exists. However, it looks like there might be a git commit hook that is running a formatter. Perhaps after that runs it formats the files and removes the diff. That results in a commit with no diff.

Perhaps you can check if my assumption is correct, and if it is, my recommendation would be to run the formatter in a step in the workflow before running this action.

![Image](https://github.com/user-attachments/assets/65cd7819-1ede-4972-91f6-7fb5e988f5ae)

**Comment by caseybaggz** [comment]
@peter-evans we do run a pre-commit hook to validate and format the code to which if this action is altering our code base, we still want to run for validation and formatting.

I feel like there is probably a window of opportunity to improve the action? I'm not familair with the GH API, but is there a way to check the files changed vs. the diffs? I believe that would solve the problem for our use case because we have 0 files changed (probably different from diffs).

What do you think?

**Comment by peter-evans** [comment]
@caseybaggz There's nothing reasonable I can do in the action to solve this (if it's what I suspect). The solution is as I described, just run the formatter before the action runs. The formatter will correct the format of the files that were causing the initial diff, and then when the action runs it will correctly find that there is no diff and not create a PR.

**Comment by caseybaggz** [comment]
Unfortunately, that doesn't make sense with our team and code base (to alter our setup just to accommodate this action). I appreciate the help and time to talk through it.
