### ISSUE TITLE
Action failing to update existing PRs on differently named fork

### ISSUE THREAD

**Issue by coleenquadros** [peter-evans/create-pull-request#3030]
I have a fork of a repo in a different org under a different name. Example if original/repo1 and my fork is copy/copy-repo1. It creates the PR since the head_repo is provided in the create request. But I am seeing an issue on v6  when updating an already existing PR where I see the following error -> ` Error: Cannot read properties of undefined (reading 'number')`

https://github.com/peter-evans/create-pull-request/blob/c5a7806660adbe173f04e3e038b0ccdcd758773c/src/github-helper.ts#L59

I was wondering if there is a way to provide the head_repo similar to what was done[ here](https://github.com/peter-evans/create-pull-request/issues/2043) when listing the pull requests and updating them.

**Comment by peter-evans** [comment]
Hi @coleenquadros 

What version of the action are you using? I fixed [an issue](https://github.com/peter-evans/create-pull-request/issues/2790) that might be related to what you are seeing in [v6.0.1](https://github.com/peter-evans/create-pull-request/releases/tag/v6.0.1).

**Comment by coleenquadros** [comment]
@peter-evans I am using v6. I have a recent fork of your repo and I am referencing the action from there

**Comment by peter-evans** [comment]
@coleenquadros Please double check and make 100% sure that you are using at least `v6.0.1`, where the fix was made. I can't tell if your fork (and the way you are referencing the forked action) is actually running the latest code. One way you could test to be sure is by not using your fork and calling `peter-evans/create-pull-request@v6`. If you still see the same issue, then I can look into it further.

**Comment by N6REJ** [comment]
I completely rewrote everything with the help of codium AI and still nothing.  I've made sure I'm using @v6.
here's the relevant output https://github.com/Bearsampp/Bearsampp/actions/runs/10043633469
https://github.com/Bearsampp/Bearsampp/tree/main/core/resources is where the finishied file should wind up 
this is the created file.  That part is working correctly. https://github.com/Bearsampp/Bearsampp/blob/update-releases/core/resources/quickpick-releases.json
https://github.com/Bearsampp/Bearsampp/blob/main/.github/combine_releases.py is the python part of the code and https://github.com/Bearsampp/Bearsampp/blob/main/.github/workflows/combine_releases.yml is the main part of the action.
I don't know what to do to fix this.  
Hopefully it can be setup to automerge once its working correctly.
