### ISSUE TITLE
Syntax error line 17

### ISSUE THREAD

**Issue by N6REJ** [peter-evans/create-pull-request#3069]
### Subject of the issue
I'm getting a syntax error on line 17.  I don't understand why.

### Steps to reproduce
run auto-merge.yml

https://github.com/Bearsampp/Bearsampp/actions/runs/10133828922/workflow
![image](https://github.com/user-attachments/assets/ee7da48d-932f-4908-bfac-c59eb083c369)

This might be related.
https://github.com/Bearsampp/sandbox/actions/runs/10133810803/job/28019373055
![image](https://github.com/user-attachments/assets/96e56c45-4879-44e9-851d-5f555cc8a940)

**Comment by peter-evans** [comment]
Hi @N6REJ 

I think line 17 is just referring to the whole `with` block. So something with the inputs is not right. Maybe it's the `title` (line 22). I'm not sure if you can escape quotes like that. Try changing to double quotes like you've done with the `body`.

**Comment by N6REJ** [comment]
thanks, you were right.
