### ISSUE TITLE
remote missing

### ISSUE THREAD

**Issue by xenoterracide** [peter-evans/create-pull-request#3085]
### Subject of the issue

The git remote went missing, I don't think its caused by this action (probably caused by github), but maybe this action could fix it?

### Steps to reproduce

Seems a recent failure. putting `git remote show origin` before it seems to have fixed it. 

https://github.com/xenoterracide/java-commons/actions/runs/10253206468/job/28365331851
https://github.com/xenoterracide/java-commons/blob/main/.github/workflows/update-java.yml#L38 (only added line to fix)

**Comment by peter-evans** [comment]
Hi @xenoterracide 

That is quite an strange error. I don't think I've seen that before.

```
  Your branch is based on 'origin/build/auto-update-java', but the upstream is gone.
    (use "git branch --unset-upstream" to fixup)
  /usr/bin/git reset --hard origin/build/auto-update-java
  fatal: ambiguous argument 'origin/build/auto-update-java': unknown revision or path not in the working tree.
```

I'm very surprised that adding `git remote show origin` fixes it. Have you tried removing that line and running it again? It's possible that GitHub's git backend just had a blip and returned that it was missing. I presume it's not missing and hasn't been deleted. 😄

**Comment by xenoterracide** [comment]
huh... I did run it twice but I guess I didn't notice the second failure happened elsewhere (dropdown on upper right shows the 2nd run) guess github was flaking yesterday. I removed the line again, this time no issue.
