### ISSUE TITLE
Support creation of one PR per file

### ISSUE THREAD

**Issue by laeubi** [peter-evans/create-pull-request#3134]
Currently I have a project where multiple files are modified but each of them should be one PR, as the number of files changes over time I can't have a matrix or similar.

So what would be useful if there is an option to create a single PR for each changed file, instead of the while changeset. The PR can then be named like `<usual branch name>-<hashcode of full path to file>`

**Comment by peter-evans** [comment]
Hi @laeubi 

It's an interesting idea for a feature, but probably not something I would want to support directly in the action.

Did you know that you can dynamically build the config for the matrix in GitHub Actions? I've used this method in the past and it works well. I recommend that as a solution to your particular case.

Here's an article describing this:
https://medium.com/@bill.nz/github-actions-dynamic-matrix-strategy-fromjson-af606f11d3f4

**Comment by laeubi** [comment]
@peter-evans thanks for the pointer, even though this looks like something that can work, the result is rather ugly to read /maintain (compared to the simple `create-pull-request` call!), so I still hope for the future to have the ability to create multiple PRs :+1:
