### ISSUE TITLE
Overcoming github's limitations on triggering CI

### ISSUE THREAD

**Issue by LecrisUT** [peter-evans/create-pull-request#3135]
I have long looked for a solution to https://github.com/orgs/community/discussions/25702, basically the issue that if you push a new commit to an open PR, it does not re-trigger the github actions. I was surprised when I saw this project used and having a PR's action just work. What special sauce is done here? Does it only work when creating/updating a PR that is different than the triggering PR?

If this works to overcome these limitation, it should be documented as a huge feature, or inversely if it doesn't work.

**Comment by peter-evans** [comment]
Hi @LecrisUT 

Unfortunately, there is no "special sauce" applied here. 😄  This action is also subject to the same platform limitation of the default `GITHUB_TOKEN`. Please see [this section](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs) of the docs for an explanation and workarounds.
