### ISSUE TITLE
create the pull request to current base branch instead of main

### ISSUE THREAD

**Issue by sagargadamsetti** [peter-evans/create-pull-request#3336]
### How to specify the pull request target branch

I want to set the base branch as the target branch for the pull request, instead of the default main branch.

**Comment by peter-evans** [comment]
Hi @sagargadamsetti 

The action defaults to the checked out branch, but you can specify it when necessary with the `base` input. See the examples [here](https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md) for use cases that involve creating pull requests targeting other pull requests.
