### ISSUE TITLE
Commit Signing Does Not Work

### ISSUE THREAD

**Issue by thetaiter-swf** [peter-evans/create-pull-request#3438]
### Commit Signing Does Not Work

I have set `sign-commits` to true, but it does not happen. I checked the code, there is nothing set to ensure that commits are signed.

### Steps to reproduce

Set up a gpg key and try setting `sign-commits` to true. It will not work.

**Comment by peter-evans** [comment]
Hi @thetaiter-swf 

You're mixing up two different methods of commit signing. Please see the documentation here: https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#commit-signing

If you want to use GPG for commit signing, leave `sign-commits` unset (`false`).
