### ISSUE TITLE
Will this work if I already created a local topic branch?

### ISSUE THREAD

**Issue by AArnott** [peter-evans/create-pull-request#3474]
I can't seem to find the inputs to make this work:

I already have a topic branch on which commits exist. I just want to push that branch to the remote and then create a PR from that branch to the default branch for the repo.

In my attempts so far, the action seems to consider the checked out topic branch as if it were the base branch, even though I specify `base: main` and `branch: auto/libtemplateUpdate` (which is the name of my local branch).

**Comment by peter-evans** [comment]
Hi @AArnott 

This action is designed specifically to create and manage the pull request branch for you. You can use it with already created branches, but it's usually for [cases where the branch is long-lived](https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another), like a `dev` branch.

My suggestion would be either:
- Refactor your workflow to just create the changes and then let the action create the branch
- Use the [GitHub CLI to create the PR](https://cli.github.com/manual/gh_pr_create) from your existing branch

**Comment by AArnott** [comment]
Thanks. Yes `gh pr create` worked fine for me.
