### ISSUE TITLE
I am geeting error while creating a pr

### ISSUE THREAD

**Issue by ansulagrawal** [peter-evans/create-pull-request#3494]
### Subject of the issue
Run peter-evans/create-pull-request@v7
  with:
    title: Auto Merge PR
    body: This PR contains an auto merge for the changes.
    branch: auto-merge-[2](https://github.com/ansulagrawal/auto-commit/actions/runs/11708392581/job/32610040355#step:9:2)024-11-06-17-04-40
    base: main
    token: ***
    commit-message: [create-pull-request] automated change
    committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
    author: ansulagrawal <559[3](https://github.com/ansulagrawal/auto-commit/actions/runs/11708392581/job/32610040355#step:9:3)9700+ansulagrawal@users.noreply.github.com>
    signoff: false
    delete-branch: false
    sign-commits: false
    draft: false
    maintainer-can-modify: true
Prepare git configuration
  /usr/bin/git config --global --name-only --get-regexp safe.directory /home/runner/work/auto-commit/auto-commit
  /usr/bin/git config --global --add safe.directory /home/runner/work/auto-commit/auto-commit
  /usr/bin/git config --local --get remote.origin.url
  https://github.com/ansulagrawal/auto-commit
  /usr/bin/git config --local --name-only --get-regexp http.https://github.com/.extraheader ^AUTHORIZATION:
Determining the base and head repositories
Pull request branch target repository set to ansulagrawal/auto-commit
Configuring credential for HTTPS authentication
  /usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
  /usr/bin/git rev-parse --git-dir
  .git
Checking the base repository state
  /usr/bin/git symbolic-ref HEAD --short
  auto-merge-202[4](https://github.com/ansulagrawal/auto-commit/actions/runs/11708392581/job/32610040355#step:9:4)-11-06-17-04-40
  Working base is branch 'auto-merge-2024-11-06-17-04-40'
  /usr/bin/git remote prune origin
Pull request branch to create or update set to 'auto-merge-2024-11-06-17-04-40'
Configuring the committer and author
  Configured git committer as 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
  Configured git author as 'ansulagrawal <[5](https://github.com/ansulagrawal/auto-commit/actions/runs/11708392581/job/32610040355#step:9:5)5939700+ansulagrawal@users.noreply.github.com>'
Create or update the pull request branch
  /usr/bin/git symbolic-ref HEAD --short
  auto-merge-2024-11-0[6](https://github.com/ansulagrawal/auto-commit/actions/runs/11708392581/job/32610040355#step:9:6)-17-04-40
  Working base is branch 'auto-merge-2024-11-06-1[7](https://github.com/ansulagrawal/auto-commit/actions/runs/11708392581/job/32610040355#step:9:7)-04-40'
  /usr/bin/git checkout --progress -B 5ef61e73-1459-40ce-a9a0-faa[8](https://github.com/ansulagrawal/auto-commit/actions/runs/11708392581/job/32610040355#step:9:8)24fd2ad8 HEAD --
  Switched to a new branch '5ef61e73-145[9](https://github.com/ansulagrawal/auto-commit/actions/runs/11708392581/job/32610040355#step:9:9)-40ce-a9a0-faa824fd2ad8'
  /usr/bin/git status --porcelain -unormal --
  /usr/bin/git diff --quiet --
  /usr/bin/git diff --quiet --staged --
  /usr/bin/git stash push --include-untracked
  No local changes to save
  Resetting working base branch 'auto-merge-2024-[11](https://github.com/ansulagrawal/auto-commit/actions/runs/11708392581/job/32610040355#step:9:11)-06-17-04-40'
  /usr/bin/git checkout --progress auto-merge-2024-11-06-17-04-40 --
  Switched to branch 'auto-merge-2024-11-06-17-04-40'
  /usr/bin/git reset --hard origin/auto-merge-2024-11-06-17-04-40
  fatal: ambiguous argument 'origin/auto-merge-2024-11-06-17-04-40': unknown revision or path not in the working tree.
  Use '--' to separate paths from revisions, like this:
  'git <command> [<revision>...] -- [<file>...]'
  Error: The process '/usr/bin/git' failed with exit code [12](https://github.com/ansulagrawal/auto-commit/actions/runs/11708392581/job/32610040355#step:9:12)8
Restore git configuration
  /usr/bin/git config --local --name-only --get-regexp http.https://github.com/.extraheader ^AUTHORIZATION:
  http.https://github.com/.extraheader
  /usr/bin/git config --local --get-regexp http.https://github.com/.extraheader ^AUTHORIZATION:
  http.https://github.com/.extraheader AUTHORIZATION: basic ***
  /usr/bin/git config --local --unset http.https://github.com/.extraheader ^AUTHORIZATION:
  Unset config key 'http.https://github.com/.extraheader'
  /usr/bin/git config --global --unset safe.directory /home/runner/work/auto-commit/auto-commi
Describe your issue here.

### Steps to reproduce
Check out at: https://github.com/ansulagrawal/auto-commit/blob/main/.github/workflows/automerge.yml

If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.

**Comment by peter-evans** [comment]
@ansulagrawal It looks like the both the `base` and `branch` were set to the same branch name.

```
...
Working base is branch 'auto-merge-2024-11-06-17-04-40'
/usr/bin/git remote prune origin
Pull request branch to create or update set to 'auto-merge-2024-11-06-17-04-40'
...
```

I can see that you've changed the workflow to use the GitHub CLI instead. So perhaps you have a working solution already. If you still need help please provide the exact workflow you are trying.
