### ISSUE TITLE
REPO_ACCESS_TOKEN is not necessary

### ISSUE THREAD

**Issue by gr2m** [peter-evans/create-pull-request#35]
Hey there, 

I was just looking for an action that would allow me to create a pull request. I read that you use `REPO_ACCESS_TOKEN` in "order to commit", but you can in fact use `GITHUB_TOKEN` to push back to the repository, I did it a several times myself. You will need to configure `user.email` and `user.name`. Example:

https://github.com/octokit/routes/blob/72f18c4272acebab61e9decc99d6e2d9b40ce2a6/.github/workflows/nightly-update.yml#L21-L24

Then the trick is to prefix the token with `x-access-token:` in the Git URL, as I've done here:
https://github.com/octokit/routes/blob/72f18c4272acebab61e9decc99d6e2d9b40ce2a6/lib/notify-about-routes-changes.js#L42

The reason this prefix is necessary is that the `GITHUB_TOKEN` is in fact an installation token (GitHub Actions is basically an internal GitHub App). But you can use installation tokens for Git access. See https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#http-based-git-access-by-an-installation

Hope that helps :)

**Comment by peter-evans** [comment]
This is very helpful! I will try and get it working with just `GITHUB_TOKEN`.

**Comment by peter-evans** [comment]
Made an update for this and bumped the version.
Please try `peter-evans/create-pull-request@v1.2.0`

Thank you!
