### ISSUE TITLE
`repo` classic PAT scope not enough for `push-to-fork`

### ISSUE THREAD

**Issue by scop** [peter-evans/create-pull-request#3510]
### Subject of the issue

I have [a repo](https://github.com/scop/wrun) using `push-to-fork`, with a bot user PAT having (only) `repo` scope as documented it needs in https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#push-pull-request-branches-to-a-fork.

The [first time the bot created a PR](https://github.com/scop/wrun/pull/90) things went fine and the PR was merged.

However, the second time it was in process of creating one, it failed to apparently sync its own working branch with the upstream repo and [errored out](https://github.com/scop/wrun/actions/runs/11638960434/job/32414485465#step:4:360) with
```
! [remote rejected] create-pull-request/patch -> create-pull-request/patch (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/update-tools.yaml` without `workflow` scope)
```

The PR's the bot user creates [do not change any files in `.github/workflows` files](https://github.com/scop/wrun/pull/98/files). However, after the first PR that had been created, some such files [had changed in the _upstream repo_](https://github.com/scop/wrun/commit/50600788cf2afaee4367ad35b1baccbc9b48a614), and I believe this caused a failure because the bot was not allowed to sync its own existing branch where it works in with that, as it was preparing to file another PR.

I [tried if setting `delete-branch`](https://github.com/scop/wrun/commit/6486afae33883df309ed897e8afebd0a823a9f1f) would have helped, but it [did not](https://github.com/scop/wrun/actions/runs/11995512269/job/33438904764#step:4:356). Adding the `workflow` scope to the bot user PAT (in addition to `repo`) did. (Aside, this is even if the bot user's repo has actions disabled, but I guess it's understandable.)

### Steps to reproduce

Follow the trail of links in the subject above.

**Comment by scop** [comment]
Suggested PR in https://github.com/peter-evans/create-pull-request/pull/3511.

On the other hand, I believe if this action was modified so that it would actually delete its working branch in push-to-fork mode instead of pushing whatever changes upstream might have to it, the issue would not trigger.

**Comment by peter-evans** [comment]
Hi @scop 

Thanks for raising this issue.

> On the other hand, I believe if this action was modified so that it would actually delete its working branch in push-to-fork mode instead of pushing whatever changes upstream might have to it, the issue would not trigger.

I think what is happening is that when there are changes on the upstream (base) then action effectively rebases the changes you are making onto that new commit graph. So when the branch is force pushed to the fork and it includes commits on the upstream that contain changes to the `.github/workflows` path, it raises this error. I'm fairly sure this is unavoidable by the action, and the correct approach is to add the `workflow` scope, as you have done.
