### ISSUE TITLE
Support create labels with color and description

### ISSUE THREAD

**Issue by trueberryless** [peter-evans/create-pull-request#3541]
### Subject of the issue

I think currently the action just creates all labels that are parsed but don't exist in the target repository, so it would be nice if we could specify a color and description for the created label. 

### Things to consider and discuss

Are we going to change the input type anyhow? How will we pass the color and description to the action? Is it possible with an object inside the array or are just strings allowed?

We need to discuss what happens when the label already exists with another color / description: Will the action override the color / description? will it ignore the color / description and just add the label with the already existing color?

Should we even make the changes that hard or wouldn't it be easier for everyone if the action just sets a random color to a new label, which would also look very colorful...

- [x] I am willing to create a PR regarding this issue

**Comment by trueberryless** [comment]
Oh, I'm sorry I unintentionally only searched for open issues when looking for something with color, my bad...

But if I understand correctly, GitHub should be responsible for the randomisation? Cause idk if it's a coincidence but I thought that in like 3 of my repos one label always got created with a grey color... But maybe I didn't pay too much attention.

Thanks for the clarification!

Btw, this is an awesome action, makes PR synchronisation a pleasure to work with ❤️

**Comment by peter-evans** [comment]
Oh, actually I think you're right, new labels do get created with a grey color.

This action doesn't explicitly create labels, it's just a side-effect from specifying labels for a pull request that don't exist yet. To change the color you would need to call [this API](https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#update-a-label), as I mentioned in [this comment](https://github.com/peter-evans/create-pull-request/issues/2765#issuecomment-1946225550).
