### ISSUE TITLE
The requested URL returned error: 403'

### ISSUE THREAD

**Issue by emign** [peter-evans/create-pull-request#410]
### stderr: 'remote: Permission to repo denied

GitHub action in **repoA** checks out **repoB** . Changes some files and creates PR resulting in this error:
https://github.com/korlibs/klock/runs/851621058?check_suite_focus=true

PAT is available under `secrets.KORGEBOT_TOKEN `

GH action .yml file is here:

https://github.com/korlibs/klock/blob/versioningWorkflow/.github/workflows/VERSIONSYNCTEST.yml

**Comment by peter-evans** [comment]
Hi @emign 

This is an auth error, so please check that the user account on which you created the PAT has `write` access to the `korlibs/korlibs-versions` repository. That is where it is trying to create a branch for the pull request.

If, alternatively, you wanted to use a fork instead, please see this section of the documentation.
https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#push-pull-request-branches-to-a-fork

**Comment by emign** [comment]
yeah of course. Thanks for enlightening me
