### ISSUE TITLE
Cannot assign secret team as reviewer

### ISSUE THREAD

**Issue by pozil** [peter-evans/create-pull-request#484]
### Subject of the issue

When a team's visibility is set to `Secret`, action will not assign the team for review.

I doubt that this is an issue with the action itself (it's likely down to GitHub API permissions) but it may be worth mentioning that limitation in docs.

### Steps to reproduce

1. Create a `secret-team` team with visibility set to `Secret`
1. Add `secret-team` to the list of `team-reviewers` from the reference example
1. Notice that the action output does indicate that the review was requested
    ```
    Requesting team reviewers 'secret-team'
    ```
1. Check the resulting PR and notice that the `secret-team` is not assigned as a reviewer

**Comment by peter-evans** [comment]
Hi @pozil 

Thanks for reporting your findings.

You are right, this is nothing to do with the action itself, but I also don't think this is a "limitation" of the GitHub API. This is how secret teams work.

> Secret teams are only visible to the people on the team and people with owner permissions. They're great for hiding teams with sensitive names or members, such as those used for working with external partners or clients. Secret teams cannot be nested under parent teams or have child teams.

https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-teams#team-visibility

Pull requests are "public" in the sense that anyone with repository read permission can see them. So you can't set a secret team as a pull request reviewer from the GitHub UI, either. If you could, it wouldn't be secret anymore.

I don't think this behaviour will be particularly surprising to users, but it might be worth mentioning in the documentation. Thank you.
