### ISSUE TITLE
Commits seem to be rebased incorrectly with `BRANCH_SUFFIX: none`

### ISSUE THREAD

**Issue by Xyene** [peter-evans/create-pull-request#51]
We have a cron that schedules `create-pull-request` to run hourly, and configured with `BRANCH_SUFFIX: none`. After the first commit, further updates are rebased in such a way that the contents of the branch do not change.

As real example, here are two commits generated:
* 12:00 AM EDT &mdash;  https://github.com/DMOJ/site/pull/1101/commits/553de5a60030e7b58e6533898d66b10ab69b1396
* 1:00 AM EDT &mdash; https://github.com/DMOJ/site/pull/1101/commits/a4878e8f267f91031c27cae8e2a71853aaa05cf4

The PR containing them is https://github.com/DMOJ/site/pull/1101, and the order they appear in is swapped.

It seems like when updating, `create-pull-request` rebases the original PR on the new code with `-Xtheirs`, instead of the other way around... so the contents of the PR branch never change.

**Comment by peter-evans** [comment]
I think `Xtheirs` is correct, but I'm not sure why the commits are reordered.

https://git-scm.com/docs/git-rebase#Documentation/git-rebase.txt---merge
> when a merge conflict happens, the side reported as ours is the so-far rebased series, starting with \<upstream\>, and theirs is the working branch. In other words, the sides are swapped.

I'll investigate this and maybe consider not rebasing, as I mentioned here: https://github.com/peter-evans/create-pull-request/issues/50#issuecomment-537349820

**Comment by peter-evans** [comment]
I refactored to not use rebase. Please see this comment: https://github.com/peter-evans/create-pull-request/issues/50#issuecomment-537437166

I will close this issue and keep the other issue open if there is any further discussion regarding the new approach.
