### ISSUE TITLE
Create commit in the current pull request

### ISSUE THREAD

**Issue by staabm** [peter-evans/create-pull-request#61]
Is it possible to append the changes with a new commit to the current PR instead of opening a separate PR?

I would use this kind of workflow based on a comment event, when certain keywords are used

**Comment by peter-evans** [comment]
@staabm You can use `BRANCH_SUFFIX: none` for the fixed branch naming strategy. If the branch already exists then it is assumed a pull request is already open (most likely by this action) and just commits to the PR branch.

In your use case, it sounds like the difficult part will be to know what pull request branch corresponds to the `issue_comment` event. If you can extract that during the workflow then you will be able to pass it to this action via `PULL_REQUEST_BRANCH`.

**Comment by peter-evans** [comment]
Had a go at fetching the branch name from an `on: issue_comment` workflow. It's not pretty, but it works. Not every issue is a pull request so when this executes for regular issues the output `steps.vars.outputs.pr_branch` will be the string "null".

```
name: Issue Comment Workflow
on: issue_comment
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get pull request branch name
        id: vars
        run: |
          issue_num=$(jq -r .issue.number ${{ github.event_path }})
          head_ref=$(curl -sL \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$issue_num" | \
            jq -r .head.ref)
          echo ::set-output name=pr_branch::"$head_ref"
      - name: Output pull request branch name
        if: steps.vars.outputs.pr_branch != 'null'
        run: |
          echo ${{ steps.vars.outputs.pr_branch }}
```

**Comment by peter-evans** [comment]
@staabm Closing this for now. Please reopen if you want to discuss further.

**Comment by staabm** [comment]
Thx for getting back to me.

I had a finally working example with: 
https://github.com/redaxo/redaxo/blob/e437092f77d471c7c3f3eb3416f467d21db49a5f/.github/workflows/csfix.yml

It turned out though, that a lot of builds are triggered using the „on-comment“ event and I was not able to filter it only to new comments on pull request.
Effectively the github actions queue was getting pretty long pretty fast with this workflow.

We changed it to use the on-label-added workflow, but this doesnt work reliable yet:
https://github.com/redaxo/redaxo/blob/master/.github/workflows/csfix.yml

Do you have some tipps on how I could at best debug a action? I dont get why no build is triggered at all in a lot of situations

**Comment by peter-evans** [comment]
Interesting. Thanks for sharing.

Debugging actions can be tricky. Lots of trial and error! Some of these tips helped me: https://github.com/actions/toolkit/blob/master/docs/action-debugging.md

**Comment by peter-evans** [comment]
Just one thing I noticed. It's best to avoid `@master` for `actions/checkout` and follow the `v1` tag. I've seen them accidentally make breaking changes on the master branch before and needed to roll back to fix people's workflows. If you're trying to debug an action it's best to be on the stable version.
```
    - uses: actions/checkout@v1
```

**Comment by peter-evans** [comment]
@staabm You might be interested in an action I've just released for slash command style "ChatOps." You mentioned that you tried a workflow using `issue_comment` events and the queue was backing up. This solution should help with that case.

https://github.com/peter-evans/slash-command-dispatch

**Comment by staabm** [comment]
thx for mentioning. looks really usefull. I will give it a try.
