### ISSUE TITLE
Dynamically update PR title

### ISSUE THREAD

**Issue by s-canchi** [peter-evans/create-pull-request#622]
### Subject of the issue

We have been using the create-pull-request GH action to update a main repo with changes from its submodule and it works great. We currently have the title hardcoded into the yml file, but it is making tracking of feature updates difficult. Is there a way to dynamically update the PR title in our main repo with the PR title in the submodule repo when the action executes ?

**Comment by peter-evans** [comment]
Hi @s-canchi 

Yes, you can update the title dynamically when the action runs. See the following section of the documentation for details:
https://github.com/peter-evans/create-pull-request/blob/master/docs/examples.md#dynamic-configuration-using-variables
