### ISSUE TITLE
git -c core.pager=cat diff 

### ISSUE THREAD

**Issue by frassinier** [peter-evans/create-pull-request#626]
### Subject of the issue

I used this action to update a lot of files, but I saw that a `Create or update the pull request branch` can be very long!
Especially with a huge amount of files!

I'm wondering why do we need this?
https://github.com/peter-evans/create-pull-request/blob/master/src/git-command-manager.ts#L100

It results in a lot of not useful logs.

### Steps to reproduce

Try to push a big amount of files 🤷

**Comment by peter-evans** [comment]
Hi @frassinier 

> can be very long

Do you mean the action takes a long time to complete? Please let me know roughly how many files were in the pull request and how long the action took to complete.

That particular git command is used in a couple of places, but the main use is to detect if the local repository is "dirty."
https://github.com/peter-evans/create-pull-request/blob/master/src/git-command-manager.ts#L156-L171

If the verbosity of that particular command is causing the action to not perform well I will take a look at improving it.

**Comment by frassinier** [comment]
Thank you for your quick answer,

Indeed, the action takes too long for +300 files. 
I used it for copying a lot of JS and CSS files, and it takes more than 30min showing files content. During this time, the action is blocked. 
I finally cancelled the job since it was quite weird to see "create pull request" being so long 🤨

**Comment by peter-evans** [comment]
@frassinier I've released a new version of the action (`v3.5.0`/`v3`) with improvements to tackle this issue.

**Comment by peter-evans** [comment]
Thanks for reporting!

**Comment by frassinier** [comment]
LGTM, thank you! 💯
