### ISSUE TITLE
Try to get author name/email from GitHub API

### ISSUE THREAD

**Issue by Cyberbeni** [peter-evans/create-pull-request#661]
The current default for the author is this: `${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>`
I think it would be better to try to get the real name and email from the GitHub API.
I just checked myself on the API and for some reason it returns null for email, even though I have a public email:
https://api.github.com/users/Cyberbeni
https://github.com/Cyberbeni

**Comment by peter-evans** [comment]
Hi @Cyberbeni 

This is a nice idea. Unfortunately, there are just too many different use cases and ways that people want to have attribution set for git commits. In previous versions of this action there used to be more complicated logic for deciding the name and email from git config, for example. In the end I've decided to keep the interface for this action as simple as possible. That means that these kind of exceptional use cases should be done outside the action and passed to the corresponding input when executed.

So my advice would be to fetch your name and email from the GitHub API using something like [github-script](https://github.com/actions/github-script). Then pass the step outputs to this action. (By the way, I don't know why your email returns null on the API. Perhaps you need to use a token with scopes to allow that to be returned.)
