### ISSUE TITLE
Disable force pushes into PR branch

### ISSUE THREAD

**Issue by onedr0p** [peter-evans/create-pull-request#664]
### Subject of the issue

I have a [schedule](https://github.com/onedr0p/home-cluster/blob/main/.github/workflows/flux-update-schedule.yaml) set up to open a PR when it notices a new version of Flux2

![image](https://user-images.githubusercontent.com/213795/102496005-d0cd4780-4044-11eb-959b-b637da2abb32.png)

I notice that it keeps force pushing master into this branch when changes are made in master, is there anyway to disable this behavior?

### Steps to reproduce

- Create schedule that opens a PR into main branch
- Let action open PR
- Commit to main branch
- Next schedule run see that the PR is updated and the branch was force-pushed into

**Comment by peter-evans** [comment]
Hi @onedr0p 

This is fundamental to how the action is designed to work and there is no option to disable it at the moment. It makes sure pull request branches up-to-date every time the action is run. For example, if the commit from the pull request was cherry-picked to the base branch then the next run of the action would detect that there is no more diff and close the pull request.

Is there a reason you don't want it to update?

If you really don't want it to update then what that effectively means is that you don't want the action to run. So one option you could try is adding a step to detect if the pull request branch exists and exit the workflow if it does.

**Comment by onedr0p** [comment]
> Is there a reason you don't want it to update?

The files that are being modified in my workflow are files that would never be changed by a human, so there's no issue of a merge conflict happening. Having the PR be up-to-date isn't really needed and I get spammed with Github notifications everytime it happens.

> So one option you could try is adding a step to detect if the pull request branch exists and exit the workflow if it does.

This is good work-around and will implement it, but would be awesome if it was built into the action as well.

Thanks!

**Comment by onedr0p** [comment]
It appears as though github actions doesn't have a way to gracefully exit a workflow, so the only way for that work-around is have the workflow fail when the branch exists which is not ideal either.

**Comment by peter-evans** [comment]
> It appears as though github actions doesn't have a way to gracefully exit a workflow based on a condition or not

Fairly sure you can just skip steps that you don't want to run without it failing the workflow.

Closing this issue, but feel free to continue the conversation.
