### ISSUE TITLE
Any easy way to set the body to the most recent commit?

### ISSUE THREAD

**Issue by bbigras** [peter-evans/create-pull-request#665]
I'm using a tool in my github actions that makes a pretty commit for me. I would like is the PR would have the same body as the commit.

**Comment by peter-evans** [comment]
Hi @bbigras 

I don't really understand what you are trying to do. Please could you show me your workflow and what you have tried?
Are you [making your own commits](https://github.com/peter-evans/create-pull-request#controlling-commits) instead of letting the action commit for you?

**Comment by peter-evans** [comment]
Closing this for now.

**Comment by bbigras** [comment]
> Are you making your own commits instead of letting the action commit for you?

You can keep it closed, but yes. I'm making my own commits (since I'm using a tool). Sorry for the late reply.
