### ISSUE TITLE
It would be great if a fetch of the base branch wasn't necessary

### ISSUE THREAD

**Issue by palewire** [peter-evans/create-pull-request#669]
I have a repo with a large master branch and a long history. The fetch step in the default routine can take more than 20 minutes to complete. It's unclear to me if this is necessary for a small new commit to be sent as a pull request. Is there some workaround this issue to speed up the process? With the defaults, in my use case this action becomes so slow it's unusable.

**Comment by peter-evans** [comment]
Hi @palewire 

Thank you for letting me know about this performance issue. I will take a look at finding an alternative way to reset the branch without using fetch. Unfortunately there is no quick workaround for now.

**Comment by peter-evans** [comment]
I've changed the `git fetch` step to `git reset` which should improve performance in your case. Unfortunately, this improvement will not apply if you are using `push-to-fork`. When pushing to a fork a shallow update is not allowed (which incidentally is why I was using `git fetch` here).

The new version is released as `v3.6.0` / `v3`.
Thanks for reporting!

**Comment by palewire** [comment]
This works great. Thank you.
