### ISSUE TITLE
Support making github sided gpg signatures for pull request commits.

### ISSUE THREAD

**Issue by AraHaan** [peter-evans/create-pull-request#708]
### Subject of the issue

I would like it where the commits generated by create-pull-request had an optional feature when can set to true (if they want it) to use github's gpg signature like you can when manually editing files on github itself.

### Steps to reproduce

If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.
N/A this is a feature request.

**Comment by peter-evans** [comment]
> use github's gpg signature like you can when manually editing files on github itself

Correct me if I'm wrong, but I don't think this is possible because GitHub's PGP private key is not accessible and/or usable on the GitHub Actions runner. However, I might be able to enable this feature for use with _your own_ PGP private key. This would be similar to the flow described here: https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification#gpg-commit-signature-verification

**Comment by AraHaan** [comment]
Well @peter-evans somehow the automerge action when using the github provided commit information somehow gpg signs the merged commits using github's key as far as I seen (and I used squash merging to merge on it's settings with update setting on their end to rebase).

**Comment by peter-evans** [comment]
@AraHaan What GitHub action are you referring to? Please could you link the repository.

**Comment by AraHaan** [comment]
this one https://github.com/pascalgn/automerge-action

**Comment by peter-evans** [comment]
The reason it works for merging in `automerge-action` is because it uses the GitHub API to perform the merges. The GitHub API obviously has access to its own private key for signing. In contrast, this action creates git commits on the Actions runner. To sign those commits the action would need access to a private key.

So I can probably find a way to enable this feature for use with your own PGP private key. It would still say "verified" next to the commit just like the GitHub signed commits.

**Comment by IsmanizarRf** [comment]
HttpsfzjxkjxshbjzhhckdnbzshgzhbznKzbxncxnnxjxjdjxjxnjxjdjxjxnjdnxnkxjhgehsjxokdjendjbzhaknsbhxjxnznbxbxjxskxjhhhabbzbxjjxjxjxknxkxjnxnxjnxnxnjxggvshjxkxnxjjxndnj bboopapzjxjnxnckxnnxjxjjzjxjjkjxjcjcjjfjfjcjjxjcjjxnbbzhgdxkkdkxnncnzbxkxkcjjxhgzhbxbxhbxjxbjzjzjjzjxj[****]()

**Comment by IsmanizarRf** [comment]
****

**Comment by IsmanizarRf** [comment]
****

**Comment by IsmanizarRf** [comment]
Https **![image](https://user-images.githubusercontent.com/76594523/107994492-b1887180-7017-11eb-8ed0-6b157cecb0a1.jpeg)**

**Comment by IsmanizarRf** [comment]
**![image](https://user-images.githubusercontent.com/76594523/107994513-c36a1480-7017-11eb-9c9a-fe7db3196d79.jpeg)**

**Comment by IsmanizarRf** [comment]
****

**Comment by IsmanizarRf** [comment]
![image](https://user-images.githubusercontent.com/76594523/107994569-e0064c80-7017-11eb-9a5b-4d277efc9163.jpeg)

**Comment by IsmanizarRf** [comment]
![image](https://user-images.githubusercontent.com/76594523/107994597-f0b6c280-7017-11eb-8207-7f39f8c49f35.jpeg)

**Comment by IsmanizarRf** [comment]
![image](https://user-images.githubusercontent.com/76594523/107994667-10e68180-7018-11eb-9ce6-7b129ba40dc3.jpeg)

**Comment by IsmanizarRf** [comment]
![image](https://user-images.githubusercontent.com/76594523/107994720-2491e800-7018-11eb-993b-ee621b3c8670.jpeg)

**Comment by IsmanizarRf** [comment]
![image](https://user-images.githubusercontent.com/76594523/107994756-34a9c780-7018-11eb-80a8-f50a6eba3bd9.jpeg)

**Comment by AraHaan** [comment]
...

**Comment by IsmanizarRf** [comment]
![image](https://user-images.githubusercontent.com/76594523/107994778-44291080-7018-11eb-8b73-46b2f49141da.jpeg)

**Comment by IsmanizarRf** [comment]
![image](https://user-images.githubusercontent.com/76594523/107994811-56a34a00-7018-11eb-80cb-a3a07b6f2c14.jpeg)

**Comment by IsmanizarRf** [comment]
![image](https://user-images.githubusercontent.com/76594523/107994843-6884ed00-7018-11eb-94d5-0c0c6029b2d2.jpeg)

**Comment by IsmanizarRf** [comment]
![image](https://user-images.githubusercontent.com/76594523/107994864-76d30900-7018-11eb-80af-62193c59b836.jpeg)

**Comment by IsmanizarRf** [comment]
![image](https://user-images.githubusercontent.com/76594523/107994889-85b9bb80-7018-11eb-953e-b914f0410dac.jpeg)

**Comment by IsmanizarRf** [comment]
![image](https://user-images.githubusercontent.com/76594523/107996130-9a974e80-701a-11eb-8b6a-7edcaed10481.jpeg)

**Comment by IsmanizarRf** [comment]
![image](https://user-images.githubusercontent.com/76594523/107996165-b39fff80-701a-11eb-8bfd-34172b92fc15.jpeg)

**Comment by IsmanizarRf** [comment]
![image](https://user-images.githubusercontent.com/76594523/107996189-c1ee1b80-701a-11eb-86b8-0686699800ee.jpeg)

**Comment by IsmanizarRf** [comment]
![image](https://user-images.githubusercontent.com/76594523/107996221-d5998200-701a-11eb-8b47-1501b937b9ba.jpeg)

**Comment by IsmanizarRf** [comment]
![image](https://user-images.githubusercontent.com/76594523/107996242-e4803480-701a-11eb-80d7-985bf20f2e43.jpeg)

**Comment by IsmanizarRf** [comment]
![image](https://user-images.githubusercontent.com/76594523/107996274-fa8df500-701a-11eb-83ab-cb007a3aadf9.jpeg)

**Comment by IsmanizarRf** [comment]
![image](https://user-images.githubusercontent.com/76594523/107996299-0679b700-701b-11eb-9167-d1c82d7eab1b.jpeg)

**Comment by IsmanizarRf** [comment]
![image](https://user-images.githubusercontent.com/76594523/107996323-172a2d00-701b-11eb-8cc1-a44b9cf8e1ee.jpeg)

**Comment by Re-acted** [comment]
README.ID

**Comment by Re-acted** [comment]
REDME.ID

**Comment by Re-acted** [comment]
HTTPS NBHZHXBB N🧱💰💰💣🧰jjhvfdbnnnbnvvmnnbbbvcddsmlkjhhhhhvvbccvvvvbbbbhhbbvfkkjkjgffhjkjhjkgffvhhf🏦🏦🏦🏦🏦🏦🏦🏦🏢🏬🏭🏚🏠🏡🏘🏫🏫🏪🏪💒🏛🏨🏦🏦🏥🏥🏦💒🏥🏦🏦🏦🏦🏦🏦🏦🏦🏦🏦🏦🏦🏦🏦🏦🏦

**Comment by davidboweninrupt** [comment]
Hi @peter-evans 

I'm not sure if this helps, but I can see dependabot is able to use the Github key so it's commits are verified.

![image](https://user-images.githubusercontent.com/76816026/117061482-2c5d5080-ad1a-11eb-949f-a94478ceb48a.png)

Perhaps it being available for apps and bots doesn't help this action.

https://github.blog/2019-08-15-commit-signing-support-for-bots-and-other-github-apps/

**Comment by peter-evans** [comment]
Hi @davidboweninrupt 

I found some more information [here](https://github.community/t/how-to-properly-gpg-sign-github-app-bot-created-commits/131364/2) about how you can achieve commit signing by _GitHub's own key_ for GitHub Apps. However, it doesn't help for GitHub Actions, unfortunately.

As I mentioned in an earlier comment, I'm fairly sure I can make this work for your own GPG key, but not GitHub's. If that's something you would be interested in using let me know.

**Comment by AraHaan** [comment]
I think that could work as well, Even if it allows the "bot" that the action on my workflow uses an PAT with to sign it using the GPG key for that account.

**Comment by peter-evans** [comment]
Ok, I'll look into adding a feature to use your own GPG key to sign commits then.

**Comment by davidboweninrupt** [comment]
Thanks for the link signing with a github app. I was chatting about that with a security researcher yesterday and it would be an answer, it's just a lot of work just to get a commit signed :)

It's kind of you to follow through on the request to add GPG signing as part of your action. I can see that being useful.

As I've looked more deeply into this it's become clear that it would be best to not include _my_ GPG for the action to use because then that secret could be used by other things to sign work as me. I'm going to look at getting a GPG key for a machine account and using that. I need to find out if I can create the PR as the machine account instead of it being me.

**Comment by AraHaan** [comment]
@davidboweninrupt you can, I do it on my submodule update workflow in https://github.com/Elskom/Sdk/

**Comment by davidboweninrupt** [comment]
@AraHaan thanks for the link to https://github.com/Elskom/Sdk/ , seeing that action helped inspire me to do the things I needed to do.

@peter-evans thanks for the action, obviously, but also thanks for keeping the documentation up to date and clear. It took my brain a while to realise, but setting the right `committer` made things awesome and now the flow in our (sadly private) repo is now beautiful.

**Comment by peter-evans** [comment]
I have the feature working. Signed commits look like this:

![image](https://user-images.githubusercontent.com/18365890/117557723-01278800-b0b1-11eb-8bae-e649c453b660.png)

**Comment by davidboweninrupt** [comment]
Everything I can see there looks good @peter-evans

**Comment by peter-evans** [comment]
Released as `v3` / `v3.9.0`

See the documentation for usage details: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#gpg-commit-signature-verification
