### ISSUE TITLE
Create pull request from an existing branch?

### ISSUE THREAD

**Issue by ma-sadeghi** [peter-evans/create-pull-request#735]
If I want to create a pull request from an existing branch, let's say `my_branch`, do I just need to set `branch` input to `my_branch`?

**Comment by ma-sadeghi** [comment]
I just tried on a toy repo and it seems it does what I want. Thanks for the great Action 👍

**Comment by ma-sadeghi** [comment]
I have another question now: I tried to use the Action to create a pull request from an existing branch, but the Action failed, complaining that it cannot push to protected branches. However, I don't use the Action to push anything (I've pushed the changes in a previous step in the parent Action), but rather to simply create a pull request. Is there something that I'm doing wrong?

**Comment by peter-evans** [comment]
Hi @ma-sadeghi 

Please see this example for creating pull requests from an existing branch:
https://github.com/peter-evans/create-pull-request/blob/master/docs/examples.md#keep-a-branch-up-to-date-with-another

Just adding your existing branch to the `branch` input will not work.
