### ISSUE TITLE
Continuous force pushes when files are deleted

### ISSUE THREAD

**Issue by stramel** [peter-evans/create-pull-request#748]
### Subject of the issue

I have a PR that is continuously being force pushed to when there are deleted files. This has resulted in over 500 force pushes.

### Steps to reproduce

https://github.com/stramel/material-design-icons-updated/pull/85

**Comment by peter-evans** [comment]
Hi @stramel 

Please could you explain more about what you think is wrong about this behaviour. When there are changes on the base which affect the pull request it's normal for it to be force updated.

**Comment by stramel** [comment]
Sorry, I was in a rush and having a hard time explaining. 

I noticed the original PR had removed (deleted) a couple icons. I have the action setup to run every 1 hour. Each time the action runs via the 1hr cron, it triggers a new force push but I'm not seeing any differences between the commits, AFAICT.

I will do some more digging but I haven't noticed this issue if there weren't deleted files in the existing PR.

**Comment by peter-evans** [comment]
Your workflow is constantly checking for updates and downloading them. Perhaps this icon set gets updated very frequently at the source so the PR you have open is constantly being updated with those changes.

**Comment by stramel** [comment]
Going to close this until I have time to investigate further. It may have been a ton of updates to the manifest file causing the issue.
