### ISSUE TITLE
Override commit

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [peter-evans/create-pull-request#750]
### Override commit created by `workflow_dispatcher`

I am creating, in a specific branch, a commit with a few changes. This commit is generated by a `workflow_dispatcher`. Then, I can get a few conflicts if I generate multiple commits in multiple PRs that are merged before I merge this one.

I would like if I launch a new workflow dispatcher with the same params, the previous PR be overwritten, removing the old commit and adding the new commit which shouldn't have conflicts.

**Comment by peter-evans** [comment]
Hi @JavierSegoviaCordoba 

Apologies, I don't really understand what you are trying to achieve. Do you have a workflow that you could show to help me understand?

**Comment by JavierSegoviaCordoba** [comment]
I would like to update a PR, dropping the previous commits, updating the PR branch to get the latest commits from the base branch, and adding a new commit, with a force push.

**Comment by peter-evans** [comment]
It's difficult to say whether this action would work for your use case. It sounds like it would not be a particularly vanilla way to use the action.

I recommend looking at the documentation and examples and trying it out yourself. I'm going to close this issue for now. If you run into a specific issue then I'll take a look and see if I can help you.

**Comment by JavierSegoviaCordoba** [comment]
I would like to talk about this again.

I want the exact same behavior dependabot has.

PR created by this action every day at 00:00. I don’t merge it. I push another commit to the main branch so this PR has a conflict. I just want it to be rebased adding the commit on top “ignoring the conflicts” when th action runs on the next day because the name branch will be the same.

**Comment by peter-evans** [comment]
@JavierSegoviaCordoba Have you tried to use the action in the way you have described? What you have described sounds like how the action actually works, unless I'm misunderstanding. Please try it and if it doesn't work how you expect then show me your workflow and I'll try and help you as best I can.
