### ISSUE TITLE
Possible to create a pull request from a tag?

### ISSUE THREAD

**Issue by franciscolourenco** [peter-evans/create-pull-request#762]
### Subject of the issue
I'm looking to create a pull request from a specific tag, or to use the alternative strategy, but using a tag as the branch name. 

Is this currently possible?

Thanks!

**Comment by peter-evans** [comment]
Hi @franciscolourenco 

Yes, you can create a pull request where the `base` of the pull request is a tag. Workflows that checkout a tag are checked out on a commit, not a branch. In these cases you must specify the `base` input. See the documentation for [events which checkout a commit](https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#events-which-checkout-a-commit). 

Perhaps what you want to do is close to this example.
https://github.com/peter-evans/create-pull-request/blob/master/docs/examples.md#use-case-create-a-pull-request-to-update-x-on-release
