### ISSUE TITLE
Required Variables and Escaping New lines

### ISSUE THREAD

**Issue by AzySir** [peter-evans/create-pull-request#779]
Hey Peter love your work!

Just wanted to ask if it was possible to put required variables down inside of a table (maybe the docs on marketplace) 

Would be greatly appreciate thanks!

**Comment by peter-evans** [comment]
Hi @AzySir 

Thank you 😄 

There are no required inputs. You can use the action like this with no specified inputs and it will use the defaults listed [here](https://github.com/peter-evans/create-pull-request#action-inputs).
```yml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
```

**Comment by AzySir** [comment]
Thanks for your reply @peter-evans - that is definitely helpful - however I keep hitting this error and I'm using defaults

` Error: The 'base' and 'branch' for a pull request must be different branches. Unable to continue`

**Comment by peter-evans** [comment]
It sounds like the workflow is running on `pull_request` events, which can be difficult to get right and I would avoid it if possible. See this example: https://github.com/peter-evans/create-pull-request/blob/master/docs/examples.md#use-case-create-a-pull-request-to-modifyfix-pull-requests

If you show me your workflow I might be able to help you.

**Comment by AzySir** [comment]
All good @peter-evans got it working as expected. Stuck on one more thing which is -

`echo "::set-output name=getplan::$(echo $plan | wc -l)` 

Trying to read this into the body of the PR - however this is an array. How could I read this into the body without killing the \n characters. I can read it in as one string, but I need it as multi strings for a Terraform plan

**Comment by peter-evans** [comment]
@AzySir See this example which shows how to escape to preserve newlines.

https://github.com/peter-evans/create-pull-request/blob/master/docs/examples.md#setting-the-pull-request-body-from-a-file

**Comment by AzySir** [comment]
Thank you my good sir you are a hero amongst men @peter-evans  - I would hope Github are sending some sort of goodies your way!! :)

**Comment by AzySir** [comment]
Both of these have been sold as per @peter-evans instructions. 

- There are no required inputs and some variables have default values (these values are used if they are not set)

- An example of escaping new line characters can be found at https://github.com/peter-evans/create-pull-request/blob/master/docs/examples.md#setting-the-pull-request-body-from-a-file

- The escaping of new characters was helpful when try to move a 'Terraform plan' output into a PR in order to wait for an approval for the Terraform apply at the next stage. (Similar to a GitLab setup, however this is not offered by default and Pete's create-pull-request repo covers this scenario 

- Great work @peter-evans !

**Comment by peter-evans** [comment]
> I would hope Github are sending some sort of goodies your way!! :)

I wish! 😆 

Glad you solved your issues. Thanks for the summary.
