### ISSUE TITLE
PR not created but Branches directly merged.

### ISSUE THREAD

**Issue by pranjal-joshi** [peter-evans/create-pull-request#788]
### Subject of the issue

Hello, I want to create a PR from `new-features`  to `main` branch on `push` event on `new-features` branch.
With your action, the `new-features` branch is directly getting merged with `main` instead of creating a PR.

Here is link for the yml file: [workflow-test.yml](https://github.com/pranjal-joshi/Screeni-py/blob/new-features/.github/workflows/workflow-test.yml)

### Steps to reproduce

GitHub Action Workflow logs: [https://github.com/pranjal-joshi/Screeni-py/runs/2481963885?check_suite_focus=true](https://github.com/pranjal-joshi/Screeni-py/runs/2481963885?check_suite_focus=true)

**Comment by peter-evans** [comment]
Hi @pranjal-joshi 

Please see this example to achieve this kind of workflow.
https://github.com/peter-evans/create-pull-request/blob/master/docs/examples.md#keep-a-branch-up-to-date-with-another
