### ISSUE TITLE
Rename default branch to main.

### ISSUE THREAD

**Issue by AraHaan** [peter-evans/create-pull-request#793]
### Subject of the issue

I been going around to the repositories that provide the github actions I use and filing to change the default branch from ``master`` to ``main``.

This is because there are only 4 of the actions I use on my workflows total out of about 4~5 workflows per repository with 3 repositories total.

This amounts to a very few github actions using ``master`` instead of ``main`` as the default branch. I think all that needs done is for ``main`` to be made from the current ``master`` and then a workflow created to "sync" ``master`` up with ``main`` by having it check out ``master`` then running ``git pull origin main`` and then ``git push`` it to that master branch. It can be automated every time a commit is pushed to ``main`` so the maintenance cost should be low with this. It also keeps things the same for those who prefer to use the ``master`` branch in their workflows instead of ``main`` and ``main`` for those who prefer that.

### Steps to reproduce

Sorry for the issue for this, love the action just would love to use it by ``peter-evans/create-pull-request@main`` instead of ``peter-evans/create-pull-request@master`` or even have it pinned on a tag, it actually really helps greatly in case there was a bug on the stable release.

**Comment by peter-evans** [comment]
I've thought a lot about how to rename the default branch across all of the GitHub actions that I maintain. There are a number of different options to try and smooth out the process, none of which I like very much for various reasons. These two points are the conclusions I've come to:

- There is no point in doing this rename as a half-measure. If I go ahead with the rename then I'll be removing all references to `master`.
- If I do the rename, I will use [GitHub's feature to rename the branch](https://docs.github.com/en/github/administering-a-repository/renaming-a-branch). The reason for this is that their feature includes automatic URL redirection, and forks of the repository can still update using the [new sync feature](https://github.blog/changelog/2021-05-06-sync-an-out-of-date-branch-of-a-fork-from-the-web/).

So I've decided the best way to go about this is to try a warn the users using `@master` ahead of time. I'll set a date for the switch and update the action on the `master` branch to issue a warning to the GitHub Actions log. The warning will advise them to switch to `@latest`, which will be a tag that follows the default branch.

There is a high chance that many users won't see the warning. That is unfortunate, but to try and avoid it means I have to compromise on the two points above. All of my documentation advises users to use the release tags, anyway. I've never made any guarantee that the default branch is stable. So I'm hoping that most users are following the documentation.

This requires a bit of planning, and I'll probably try and switch all the GitHub actions I maintain at the same time.

**Comment by peter-evans** [comment]
After a bit of testing how the redirection works, and whether or not adding a tag called `master` breaks fork sync'ing and redirection, I've decided on a different approach.

1. Use GitHub's feature to do the branch rename.
2. Create a new branch called `deprecated-master` and tag it as `master`.
3. Add a warning to the action in branch `deprecated-master` and advise users to move to `@main`. The warning will include a date when the `master` tag will be removed.
4. Remove the `master` tag, allowing redirection to `main`

Using a tag instead of a branch called `master` should prevent git checkout/fetch, but still allow the action to be referenced in workflows.

**Comment by peter-evans** [comment]
Renamed the default branch to `main`. The `deprecated-master` branch will be removed after June 30th.

**Comment by AraHaan** [comment]
👌
