### ISSUE TITLE
Scheduled actions raise duplicate PRs

### ISSUE THREAD

**Issue by jacobtomlinson** [peter-evans/create-pull-request#80]
This is a really awesome action. Thanks for your efforts here. 🎉

I have a scheduled action which runs hourly and sometimes makes changes to the repo based on external resources.

If the action doesn't make any changes to the repo then `create-pull-request` succeeds but doesn't raise a PR. Great!

If my action does make changes then `create-pull-request` opens a pull request for me. Also great!

If I haven't merged that PR by the time it runs again it makes and same changes and raises a duplicate PR with the same name and diff. Less great...

Is it possible to add support for not raising duplicate PRs in this case? Potentially by checking open PRs for the same title or diff?

**Comment by matfax** [comment]
I'm facing a similar use case.
Maybe try `branch-suffix: none` for the start. That should prevent the duplicate PRs.

**Comment by peter-evans** [comment]
@jacobtomlinson I think your use case fits [Strategy B - Create and update a pull request branch](https://github.com/peter-evans/create-pull-request#strategy-b---create-and-update-a-pull-request-branch).

As @matfax suggested, if `branch-suffix` is set to `none` it will create the pull request branch if it doesn't exist and then any subsequent changes will be updated to the same branch name.

**Comment by jacobtomlinson** [comment]
Ah ok! I saw this line

> Any subsequent changes will be committed to the same branch and reflected in the existing pull request.

and assumed it would only raise a single pull request. If I merge the pull request and then new commits are added is another pull request raised?

**Comment by peter-evans** [comment]
Yes, if you merge or close the pull request another one will be created.

I will revise the wording of that sentence and make it clearer.

**Comment by jacobtomlinson** [comment]
Awesome! Again, thank you for your work here!

**Comment by jacobtomlinson** [comment]
Another quick question. If the repo uses "squash and merge" for it's merging strategy will this cause problems with using a single branch?

**Comment by peter-evans** [comment]
I don't think so. The only possible problem right now is that there is no rebase feature. So it's best to delete the branch after you merge or close the PR. I'm thinking about adding a rebase feature so this won't be a problem.

**Comment by jacobtomlinson** [comment]
> So it's best to delete the branch after you merge or close the PR.

I hadn't thought about that. I'll be sure to do that. I may even set branches to be [automatically cleaned up](https://help.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches).

**Comment by jacobtomlinson** [comment]
Looks like this has been resolved in 6342438.
