### ISSUE TITLE
permissions are not documented

### ISSUE THREAD

**Issue by Akuli** [peter-evans/create-pull-request#809]
### Subject of the issue

If you use `permissions` in the workflow, you need to add this:

```
permissions:
  contents: write
  pull-requests: write
```

I figured this out by trial and error. Would be nice to mention it in readme. (The default is all permissions, so you can just leave it out if you are brave)

### Steps to reproduce

Doesn't really apply, but here are steps to discover the problem and figure out the correct permissions:

1. CI not working
2. Fix the problems. `create-pull-request` fails, but imagine that it's because you are doing something slightly differently on your own fork launching the action in an unusual way.
3. Realize that you didn't actually fix the CI
4. Copy/paste all permissions from GitHub's docs
5. Delete the copy/pasted permissions one by one, committing and pushing, until the build starts failing again. Then add back what was last deleted. Between every successful push, remember to delete the created PR and its branch.
6. Submit a one-line pull request that fixes the permissions. You created one line of code in 4 hours, very efficient, yay

**Comment by peter-evans** [comment]
@Akuli Thank you for this reminder. This is a [fairly new feature](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/) of GitHub Actions and I hadn't got around to adding something in the documentation about it.

Updated the readme 👍

**Comment by hartwork** [comment]
For anyone else who looked for "permissions" in the readme but didn't find it, it's this commit: 670e508eb6d1b375875194f0aaf110a9041ed260
