### ISSUE TITLE
Error: Not Found

### ISSUE THREAD

**Issue by donn** [peter-evans/create-pull-request#870]
### Subject of the issue

No PR is created and the CI fails. Unknown reason. Only diagnostic is an `Error: Not Found` message. 

### Steps to reproduce

https://github.com/openlane-bot/openlane-tool-updater/runs/2826500612

**Comment by peter-evans** [comment]
Hi @donn 

Please change this line to just be the format `owner/repo`.

```diff
-   push-to-fork: https://github.com/${{ github.repository_owner }}/OpenLane
+   push-to-fork: ${{ github.repository_owner }}/OpenLane
```

**Comment by donn** [comment]
Ah, that did the trick. Sorry (and thank you so much for the prompt reply!)
