### ISSUE TITLE
Cant find description what happen if pull exist

### ISSUE THREAD

**Issue by 6543** [peter-evans/create-pull-request#893]
is there a option for force-push onto existing branch?
does it just fail?
...

**Comment by peter-evans** [comment]
Hi @6543 

If you mean using an existing branch for the `branch` input, then yes, it will just force update that branch by default. However, I would not advise this. I don't know of any good use cases where you would want to use an existing branch. If you explain what you are trying to do I might be able to help.

Also check out the examples to see if anything fits your use case.
https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md
