### ISSUE TITLE
undifined outputs?

### ISSUE THREAD

**Issue by eitsupi** [peter-evans/create-pull-request#914]
Thank you for your great project.

### Subject of the issue

[actionlint](https://github.com/rhysd/actionlint) (and [superlinter](https://github.com/github/super-linter) incorporating actionlint) will give an error for this action's sample that "pull-request-url is not defined".

### Steps to reproduce

The result entered in actionlint is as follows.

https://rhysd.github.io/actionlint/#eJyNVMFu00AQvecrRhUoUpEdFW6rqkqFEBwAVRE9VTms7Ulsst41O7NJo5J/Z2ynYW1S4JCDZ9+8eTNvJt9dRmoCkHvUjHfBmAX+CEjcBgF8sJQ4qyBkwXJIjICIuydibKhHASQQCEmBzrlylmZ5ifnGBZ5v305OEKtrVPBFbxDyUts1ErCDRmqC74seoV1dBYUUgzevCW7kvXGeU37kMd37Tji0ymExYqkKBXnjT9+9xgYZfYJb3ersspNWQ3LUMN++OyXsKi7V6QtE7gZF2KunJyCUXKb07vYbHA4RJnd1XXFSI5Fei8D7puuj7+APnEhR8LHiTyGDa+sEZfbztZQNWSqImyhBBy6d76sfETJu56U8XJ8JzqVdT+mRND1PStXautVKwUobwugh89rmpQJ81HVjZESaxVSKEAUamWTyDGQf4nyu2Ej304cPPcFyOIhpXMoVewU/owi8OLXW+P6t6NyBS3aF3k/psluXEfI2sEvWaNF3CdkeHs44vny4Wk4GmRJQUDLLgs9mvwc3+8fqRBxGZ2ho3NWZdsRVV3fqokWVMLXO4GhfJzHVtsKdGPwSgFHXSYQaKnE7GQoNQrWuLMtvGK8rI505K15exeZ7veLnrRmfZHv8INffBKbhScciMC8dXMSHC19DnaEXou7C2j+YVO43PVKl8awT22MPh4u/c94vPv8fYfCmZfsFyPV/zw==

![image](https://user-images.githubusercontent.com/50911393/130353407-fdbfa1d7-2847-49a7-b7e5-a7965986927b.png)

**Comment by peter-evans** [comment]
Hi @eitsupi 

I'm not really sure what this tool is checking, but maybe it's complaining because `pull-request-url` is missing from the `action.yml` file here:
https://github.com/peter-evans/create-pull-request/blob/main/action.yml#L67-L69

I just forgot to add `pull-request-url` and `pull-request-operation` to that file. It doesn't actually prevent you from using the outputs, it's just metadata.

I'll add them and hopefully that will satisfy the linter.

**Comment by peter-evans** [comment]
Released a fix for the missing outputs in `v3.10.1` / `v3`

Thanks for reporting!

**Comment by eitsupi** [comment]
Thank you for the quick response and quick fix !

> I just forgot to add `pull-request-url` and `pull-request-operation` to that file. It doesn't actually prevent you from using the outputs, it's just metadata.

Yes, I am using this action conveniently and I have confirmed that it is working fine.
So I was surprised to see an error when I tried superlinter yesterday.

**Comment by eitsupi** [comment]
I've read the actionlint documentation a bit more, and it seems that actionlint has an internal list generated from the action.yml of some GitHubActions.
So this change is expected to be incorporated here after a while.

https://github.com/rhysd/actionlint/blob/d14a1896c1f8b1fccb5204e1873595232535ce04/popular_actions.go#L1620-L1645

**Comment by peter-evans** [comment]
Oh, I see. Interesting. I was wondering how it could be doing the static analysis for the linting and now it makes sense.
