### ISSUE TITLE
Create PR with specific file

### ISSUE THREAD

**Issue by aminvakil** [peter-evans/create-pull-request#920]
### Subject of the issue

There are some cases which multiple files have been changed and you want to create multiple PRs regarding each file.

### Steps to reproduce

https://github.com/aminvakil/nvchecker/issues/99
https://github.com/aminvakil/nvchecker/pull/249/files

I can successfully create two issues using this workflow, but only one PR gets created as it's adding all changed files in a commit and creating a PR.

Thanks for your brilliant actions!

**Comment by peter-evans** [comment]
Hi @aminvakil 

Yes, all changes will be included. There are some solutions [described here](https://github.com/peter-evans/create-pull-request/issues/909#issuecomment-900743899) for avoiding unwanted files in the pull request. However, in your case, it looks like the best way to solve it is to separate the large job you have [here](https://github.com/aminvakil/nvchecker/blob/main/.github/workflows/ci.yml) into multiple jobs, one job for each pull request you want to make.

**Comment by aminvakil** [comment]
@peter-evans Yeah, you're right!

I separated them into three jobs and all is good now, thanks again for your work!
