### ISSUE TITLE
Support custom checkout path

### ISSUE THREAD

**Issue by bastianeicher** [peter-evans/create-pull-request#94]
The `actions/checkout` task allows you to specify a custom checkout `path` relative to the workspace. Would be great if `create-pull-request` could support that.

**Comment by peter-evans** [comment]
Released an update with a `path` input. It should now be available on the `v2` major version.

Thank you for making this request!

**Comment by bastianeicher** [comment]
Awesome! Thanks for the quick implementation. :)
