### ISSUE TITLE
Expose as an npm module

### ISSUE THREAD

**Issue by dontcallmedom** [peter-evans/create-pull-request#949]
Thanks for this github action which is extremely useful!

I have a recent case where I would like to call it not as part of a declarative yml workflow, but instead from a node script run in such a workflow.

Would it be possible to expose its features through an npm module? for instance, [@jsdevtools/npm-publish](https://github.com/JS-DevTools/npm-publish#javascript-function) is available both as declarative github action and an npm module.

**Comment by peter-evans** [comment]
Hi @dontcallmedom 

Glad to hear you've found it useful.

I don't think it would be difficult to publish this, but I'm not sure if it would work as expected. I've probably made a lot of assumptions that this is running as a GitHub action. Let me see if I can test this before deciding to publish.

**Comment by dontcallmedom** [comment]
just to be extra clear, the goal would be to use it as a library used in a script run as part of a github action (I'm not sure if it helps in any way)

**Comment by peter-evans** [comment]
I've taken a first look at this and realised that I would need to refactor the action entrypoint a bit to make this work. So I'll take a look at that next.

**Comment by peter-evans** [comment]
@dontcallmedom I'm having seconds thoughts about publishing this as a library. It only makes sense to run this in an GitHub actions environment anyway, so if possible I would like to see if we can achieve what you want to do in a GitHub Actions workflow. Please could you explain your use case? Presumably you want to execute the action multiple times for a number of different cases?

**Comment by dontcallmedom** [comment]
yes, the purpose would be to generate multiple pull requests.

More specifically, I would like to remove multiple entries from a single JSON file, where each of these removals would be proposed as a separate pull request. The said entries can only be determined at run time.

**Comment by peter-evans** [comment]
I would suggest using the [job matrix](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) construct to execute multiple jobs. Each job would run checkout, modify part of the JSON file, and then call create-pull-request. You might need a prerequisite job to determine the entries to be removed which is then passed to the matrix job.

**Comment by dontcallmedom** [comment]
thanks a lot for that advice!

I didn't think one could do use dynamic input to the job matrix, but I'm now [finding precedents for that](https://tomasvotruba.com/blog/2020/11/16/how-to-make-dynamic-matrix-in-github-actions/), so I'll explore that path instead.

I'll let you determine if you want to keep the issue open or close it as WONTFIX :)

**Comment by peter-evans** [comment]
As an alternative to the job matrix, the prerequisite job to determine the entries could then fire `repository_dispatch` events for each entry. Each `repository_dispatch` workflow would then run separately to create a PR. The repository dispatch API is [quite easy to call in javascript](https://github.com/peter-evans/repository-dispatch/blob/main/src/main.ts#L19-L24), so that could be an option if you wanted to do it in a script as you originally intended.

I'll close the issue for now, but feel free to continue this discussion.
