### ISSUE TITLE
[Feature Request] Use base option *only* if working base doesn't exist

### ISSUE THREAD

**Issue by katelovescode** [peter-evans/create-pull-request#969]
### Subject of the issue

When creating a tag this action fails, with the error here:
https://github.com/peter-evans/create-pull-request/blob/95767e7d51a7ebe6b4820b6ee9432ed9e747ef89/src/create-pull-request.ts#L96

I would supply a `base` option of `develop` but I don't want *every* CPR in my action to be based off of develop.  I want it to default to the working base and only use `develop` if it doesn't *have* a working base.  Even better, I'd love for it not to run at all on commits (or be able to turn off commits as an option)

### Steps to reproduce

https://github.com/pieforproviders/pieforproviders/actions/runs/1369355257 failed run
https://github.com/pieforproviders/pieforproviders/blob/develop/.github/workflows/compile-mermaid.yml workflow

**Comment by peter-evans** [comment]
Hi @katelovescode 

> Even better, I'd love for it not to run at all on commits (or be able to turn off commits as an option)

If you don't want the workflow to run at all for tag pushes then you can add a filter with `tags-ignore`. The workflow should only run on branch pushes then.

```diff
on:
  push:
    paths:
      - '**/*.mermaid'
      - '**/*.mmd'
      - '**/*.md'
+   tags-ignore:
+    - '**'
```
