### ISSUE TITLE
Does not create PR from self-hosted runner

### ISSUE THREAD

**Issue by genryxy** [peter-evans/create-pull-request#971]
Thank you for this awesome GitHub Action! I have a problem with it. I have a self-hosted runner for running some pieces of code. After finishing it is necessary to publish these results to GitHub repository. For this purpose I use this Action. 
It is [good](https://github.com/artipie/helm-adapter/runs/4001719684?check_suite_focus=true#step:6:94) at creating a new branch with saved changes that were made. But it [fails ](https://github.com/artipie/helm-adapter/runs/4001719684?check_suite_focus=true#step:6:99) to create a new pull request with such message exception `failed, reason: self signed certificate in certificate chain`.
How this can be fixed? Why the problem with certificate is occurred only on the last step?

**Comment by peter-evans** [comment]
Sorry I couldn't help you any further with this. Perhaps you managed to get it working?

I'm going to close this now because it looks like there is nothing I can do further in terms of changes to the action to help in this scenario. If it becomes clear that there is some change I can make to support this, then I'll reopen.

**Comment by genryxy** [comment]
@peter-evans thank you for your help. I did not get over the error of creating a PR from a self-hosted runner but using of a github-hosted runner for doing this action resolved my problem. I just separated workflow into two steps where the second one depends on the first step. This could be found [here](https://github.com/artipie/helm-adapter/blob/master/.github/workflows/benchmarks.yml)
