### ISSUE TITLE
Output the commit sha (of pull request's head)

### ISSUE THREAD

**Issue by hayd** [peter-evans/create-pull-request#974]
I am looking to workaround #48 by running the tests in the action and labelling the commit sha ✅ or ❌ .

One way to do that is to get the commit sha and use it with [github-status-action](https://github.com/marketplace/actions/github-status-action):

1. create pull-request
2. set commit status to pending (requires knowing the commit sha)
3. run tests with [continue-on-error](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error)
4. label commit status with [previous step's outcome](https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context)

_I believe setting the commit status like this would also be a useful option for create-pull-request itself._

Could the PR head commit sha be made available as an output?
(It's possible that `git rev-parse pr/${{ steps.cpr.outputs.pull-request-number }}` or similar works already...)

Edit: Atm I have this solution:
https://github.com/hayd/deno-udd/blob/ab0112ff1c756e8c812e0e67dace39cb52fbc00e/.github/workflows/udd.yml#L19-L53

**Comment by peter-evans** [comment]
Hi @hayd 

Interesting idea!

I've added new output `pull-request-head-sha` to the action. It's released as `v3.11.0` / `v3`.

**Comment by hayd** [comment]
Thanks for the speedy addition!

I guess you could actually have [the above](https://github.com/hayd/deno-udd/blob/ab0112ff1c756e8c812e0e67dace39cb52fbc00e/.github/workflows/udd.yml#L19-L53) more simply by skipping the pending:

1. do modification or whatever e.g. update dependencies
2. run tests with continue-on-error
3. create pull request
4. [label the commit status](https://docs.github.com/en/rest/reference/repos#create-a-commit-status) of pull-request-head-sha with the outcome of the test step

In that way 4. could be an optional flag(s) of create-pull-request.
e.g. commit-status-state, commit-status-description, commit-status-context ?

**Comment by peter-evans** [comment]
> In that way 4. could be an optional flag(s) of create-pull-request.

The overall idea is great, but I think it's best to keep updating the commit status to a separate step/action. I'm trying not to bloat this action and make it do too much, and I've even split features out into their own action like [create-or-update-project-card](https://github.com/peter-evans/create-or-update-project-card).
