### ISSUE TITLE
Support tagging the commit

### ISSUE THREAD

**Issue by marcofugaro** [peter-evans/create-pull-request#989]
### Subject of the issue

I want to tag the commit created by this action.

Right now, I am tagging the repo with just `git tag v1.2.3`, and then creating the pull request.

However I am not sure if tags are pushed, since the `--tags` option is missing.

https://github.com/peter-evans/create-pull-request/blob/d8e8e547ccc5ee4e996943b0c447d091f6d0505f/src/create-pull-request.ts#L185-L189

I think it would be enough adding that option to git push.

**Comment by peter-evans** [comment]
Hi @marcofugaro 

These are the two options I would suggest:

1. Create you own commit before the action runs and tag the commit during that step. See [here](https://github.com/peter-evans/create-pull-request#controlling-commits).
2. Tag the commit in a step after the action runs. You can even use the action output `pull-request-head-sha` to get the commit SHA of the pull request branch. See info on outputs [here](https://github.com/peter-evans/create-pull-request#action-outputs).

**Comment by marcofugaro** [comment]
Thank you so much!
