### ISSUE TITLE
Update body when PR exists

### ISSUE THREAD

**Issue by maleadt** [peter-evans/create-pull-request#99]
Thanks for developing this action, works great!

I was wondering if it would be possible to update the PR body when the branch exists already. To simplify review, I add some details about the commit to the PR's body, but when it gets updated with a different commit that information is out-of-sync.

**Comment by peter-evans** [comment]
@maleadt, glad to hear it works well for you.

Thanks for pointing this out. Currently, most of the fields of the PR will be updated, it's just the `title` and `body` that won't be. I will work on adding this missing feature.

**Comment by peter-evans** [comment]
Released and updated `v2` with this feature. Thanks for reporting!
