### ISSUE TITLE
 Please check info about this GitHub Action

### ISSUE THREAD

**Issue by varunsh-coder** [peter-evans/create-pull-request#993]
Hi @peter-evans,  I am collating security related information about GitHub Actions to calculate minimum `GITHUB_TOKEN` permissions and restrict outbound traffic to allowed domains. Request you to please check info about couple of your Actions [here](https://github.com/step-security/secure-workflows/tree/main/knowledge-base/peter-evans) - specifically the reasons for the token permissions and outbound calls. If something looks off or needs to be changed, do let me know. Thanks!

**Comment by peter-evans** [comment]
Hi @varunsh-coder 

It looks correct for the default case, but be aware that outbound URLs in many actions (including official ones like actions/checkout) will change depending on their environment. For example, users running GitHub Enterprise will be using a different outbound URL.

See these points in the code where the outbound URL can change:
https://github.com/peter-evans/create-pull-request/blob/main/src/github-helper.ts#L27
https://github.com/peter-evans/create-pull-request/blob/main/src/git-auth-helper.ts#L117-L125

**Comment by varunsh-coder** [comment]
Thanks @peter-evans! I have created an [issue](https://github.com/step-security/secure-workflows/issues/65) to have environment agnostic domain info for GitHub endpoints in the KB. 

Is it ok if I create a similar issue to validate info for other Actions that you own, as I add their info to the KB in the future?

**Comment by peter-evans** [comment]
Sure, but I'll mainly be going from memory and a quick scan of the code to remind myself what endpoints it was using. I can't guarantee that it will be correct. Ideally, I think you would need a way to test it for your Secure Workflows tool.

**Comment by varunsh-coder** [comment]
> Sure, but I'll mainly be going from memory and a quick scan of the code to remind myself what endpoints it was using. I can't guarantee that it will be correct. Ideally, I think you would need a way to test it for your Secure Workflows tool.

Thanks @peter-evans! Yes, just a quick check would be great. I do have a way to correlate outbound traffic with an Action at runtime. This is an example: https://app.stepsecurity.io/github/varunsh-coder/actions-playground/actions/runs/1527060180

Closing this issue. Thanks again!
